ansible/ansible-ai-connect-service

- ansible_wisdom/ai/api/tests/test_views.py
- ansible_wisdom/ai/api/views.py
Jira Issue: https://issues.redhat.com/browse/AAP-25002
Anonymize the results from the _generation_ and _explanation_ endpoints.
2. `make start-backends`
3. `make create-application`
4. Configure `ansible-ai-connect-service` to use a Model Provider serving generations/explanations.
5. `POST` requests, check for anonymized results.
Unit Tests.
> AAP-25002: Apply anonymizer to playbook generation and explanation output

- ansible_wisdom/ai/api/views.py
This PR does not need a corresponding Jira item
Upstream mode inferencing is currently blocked.
2. ...
3. ...
> upstream permissions

- ansible_wisdom/ai/api/model_client/tests/test_wca_client.py
- ansible_wisdom/ai/api/model_client/wca_utils.py
- ansible_wisdom/ai/api/tests/test_formatter.py
Fixes changes that were implemented prior to https://github.com/ansible/ansible-ai-connect-service/pull/1126 merging.
Relies on existing unit tests.
None
> black fixes

- ansible_wisdom/main/settings/base.py
- ansible_wisdom/main/static/styles.css
- ansible_wisdom/main/templates/base.html
- ansible_wisdom/main/templates/registration/login.html
- ansible_wisdom/main/tests/test_urls.py
- ansible_wisdom/users/templates/users/community-terms.html
- ansible_wisdom/users/templates/users/home.html
Jira Issue: <https://issues.redhat.com/browse/AAP-24975>
Remove all inline CSS and move it to styles.css file to avoid style-src unsafe-inline
2. Run wisdom_service
3. No errors about style-src unsafe-inline are present in the DEV console in your browser while using web site.
> [DAST] Lightspeed Downstream: CSP: style-src unsafe-inline

- ansible_wisdom/ai/api/tests/test_views.py
- ansible_wisdom/ai/api/views.py
The collect backend is not ready yet.
> schema2: don't send playbookGenerationAction event until next week

- .flake8
- .github/workflows/pip_audit.yml
- .github/workflows/pip_compile.yml
- .github/workflows/pre-commit.yml
- README.md
- ansible_wisdom/main/settings/base.py
- docs/pycharm-setup.md
- pyproject.toml
- sonar-project.properties
- tools/configs/supervisord.d/auto-reload.conf
- tools/configs/uwsgi.ini
- tools/docker-compose/compose.yaml
- tools/scripts/auto-reload.sh
- tools/scripts/launch-wisdom.sh
- tox.ini
- wisdom-service.Containerfile
Jira Issue: <https://issues.redhat.com/browse/AAP-19331>
Continue the transition to `ansible_ai_connect`.
See: https://github.com/ansible/ansible-ai-connect-service/pull/990
See: https://github.com/ansible/ansible-ai-connect-service/pull/883
> continue the ansible_ai_connect transition

- ansible_ai_connect/ai/api/model_client/grpc_client.py
Jira Issue: <https://issues.redhat.com/browse/AAP-24832>
Certification verification should be enabled by default, and we have nothing to prevent us from it anymore.
1. We are not using gRPC in production nothing to test
> AAP-24832: Enable certificate verification

- ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
- ansible_ai_connect/ai/api/model_client/wca_client.py
- ansible_ai_connect/ai/api/model_client/wca_utils.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
Jira Issue: https://issues.redhat.com/browse/AAP-25873
Quick fix to support improved exception handling for playbook generation/explanation.
I've added unit tests for the handled scenarios.
2. Unit tests pass.
Unit tests.
> AAP-25873: Dirty fix for 400 Bad Request from WCA requests

- requirements-aarch64.txt
- requirements-dev-aarch64.txt
- requirements-dev-x86_64.txt
- requirements-dev.in
- requirements-x86_64.txt
- requirements.in
Fix for CVE-2024-39689
Just to make sure all CI tests passed
n/a
CI tests
> Fix for CVE-2024-39689

- ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
- ansible_ai_connect/ai/api/model_client/wca_client.py
Jira Issue: [AAP-25884](https://issues.redhat.com/browse/AAP-25884) & [AAP-25894](https://issues.redhat.com/browse/AAP-25894)
Implement prometheus metrics for WCA playbook explaination/generation APIs.  Following metrics are added:
- wca_codegen_playbook_hist
- wca_codegen_playbook_retry_counter
-  wca_explain_playbook_hist
-  wca_explain_playbook_retry_counter
Unit test cases are included.
See above
> Prometheus metrics for WCA playbook expgen APIs

- ansible_ai_connect/users/authz_checker.py
- ansible_ai_connect/users/tests/test_authz_checker.py
Jira Issue: https://issues.redhat.com/browse/AAP-25245
Removes the `check` method in `authz_checker.py` from the `BaseCheck` class and all it's implementations. This is part of the seat management cleanup.
1. Pull down the PR.
2. Run the wisdom service locally.
3. Make sure you can still log in and the `/me` endpoint works.
> cleanup: remove check methods and relevant unit tests from authz_checker

- MANIFEST.in
https://issues.redhat.com/browse/AAP-26876
Ensure the `styles.css` static file is included in the manifest.
> Fix styles inclusion

- ansible_ai_connect/users/authz_checker.py
- ansible_ai_connect/users/tests/test_authz_checker.py
Jira Issue: [AAP-26593](https://issues.redhat.com/browse/AAP-26593)
Add Prometheus histograms and more logs to Authz APIs for better traceability on those APIs.
Unit tests are included.
See above.
> Add histograms and more logs to Authz APIs

- ansible_ai_connect/ai/api/serializers.py
- ansible_ai_connect/ai/api/tests/test_serializers.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
- tools/openapi-schema/ansible-ai-connect-service.yaml
Jira Issue: https://issues.redhat.com/browse/AAP-27155
Removes unused fields from inlineSuggestionFeedback
N/A
Unit tests updated.
> remove activityId and latency from inlineSuggestionFeedback

- .tekton/ansible-ai-connect-service-pull-request.yaml
- .tekton/ansible-ai-connect-service-push.yaml
> update clamav bundle values

- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/users/views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-27332>
2. ...
3. ...
> me/summary: show trial information

- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/users/serializers.py
- ansible_ai_connect/users/views.py
- tools/openapi-schema/ansible-ai-connect-service.yaml
Updating openAPI Schema for:
Jira Issue: <https://issues.redhat.com/browse/AAP-26574>
As a new endpoint is being added, a new serializer must be created as well. This PR creates a new serializer which parses the html content from the /me/markdown endpoint
2. Run the service
3. Access localhost:8000/api/v0/me/markdown and ensure content appears
4. Access s[waggerUI](http://localhost:8000/api/schema/swagger-ui/#/me/me_summary_retrieve) and validate example schema
> Update openAPI Schema for /me/summary endpoint

- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/users/serializers.py
Jira Issue: [AAP-27646](https://issues.redhat.com/browse/AAP-27646)
Update the left panel of VS Code extension that shows the information of the user based on feedback obtained in the Jul 23 meeting.
- **Note:** The "AFTER" image also contains a small fix in the VS Code extension to remove the extra vertical spaces occupied by the HTML \<p\> tag generated by the marked parser.  The VS Code extension PR for that will be created shortly. --> The PR created: https://github.com/ansible/vscode-ansible/pull/1448
Unit test case is included.  Manual testing was also done.
2. Run uni tests
See above
> One Click Trial left panel UI adjustments

- requirements-aarch64.txt
- requirements-x86_64.txt
- requirements.in
```
Name | Version | ID | Fix Versions
langchain-community | 0.2.5 | GHSA-q25c-c977-4cmh | 0.2.9
```
> Upgrade langchain and langchain-community to latest versions

- ansible_ai_connect/main/static/styles.css
- ansible_ai_connect/users/templates/users/trial.html
Jira Issue: https://issues.redhat.com/browse/AAP-27650
Adjusting padding and formatting of checkboxes. Decreasing padding around bottom buttons
> AAP-27650: Adjusting /trial UI

- ansible_ai_connect/users/templates/users/trial.html
Jira Issue: https://issues.redhat.com/browse/AAP-27870
> Removing 'this will only apply to you...' text

- ansible_ai_connect/users/tests/test_views.py
- ansible_ai_connect/users/views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-28144>
Restrict who can access the /trial end-point.
Unit-tests
> AAP-28144: prevent the non-AAP users from reaching the /trial page

- .github/workflows/pr_deployment_test.yml
> PR testing run fix

- ansible_ai_connect/main/static/styles.css
- ansible_ai_connect/users/templates/users/trial.html
Jira Issue: <https://issues.redhat.com/browse/AAP-27828>
Restructure /trial page UI elements to include required information from marketing and legal
unit-tests
> AAP-27828 | Trial Page UI Adjustments

- ansible_ai_connect/organizations/models.py
- ansible_ai_connect/organizations/tests/test_organizations.py
- ansible_ai_connect/users/serializers.py
- ansible_ai_connect/users/views.py
Jira Issue: https://issues.redhat.com/browse/AAP-27334
1. Open VS Code
2. Connect with a user eligible to the Trial
3. Ensure the left panel is as expected
> AAP-27334: trial view for VS Code left panel

- ansible_ai_connect/ai/api/model_client/wca_client.py
- ansible_ai_connect/ai/api/permissions.py
- ansible_ai_connect/users/models.py
- ansible_ai_connect/users/views.py
> replacing code with organization.has_api_key org attribute

- .tekton/ansible-ai-connect-service-push.yaml
The slack message will contain the link to the failed run
will be like:
> Konflux on-push failure slack the pipelineRun link

- ansible_ai_connect/main/static/styles.css
- ansible_ai_connect/users/templates/users/trial.html
- ansible_ai_connect/users/tests/test_views.py
- ansible_ai_connect/users/views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-28829>
This PR updates the main trial panel for the One Click Trial feature as suggested.  The updated panel looks like
In addition to a manual test, unit tests are updated according ly.
2. Run unit tests.
See above.
> Update strings on main trial panel

- ansible_ai_connect/users/templates/users/trial.html
Jira Issue: <https://issues.redhat.com/browse/AAP-29599>
The logout button was missing on the trial web page when the trial is active or expired.
Manually tested in the local environment
2. Start local server
3. Edit conditional statements in trial.html to see the logout button is displayed when ever the user is authenticated.
See above.
> Move the logout button out of the if block for start trial

- wisdom-service.Containerfile
This reverts commit 7a7418ab46f65b44afe7b0c6d5774c7fafc4cb28.
> Revert "container: refresh browserslist (#1270)"

- ansible_ai_connect_admin_portal/package-lock.json
- ansible_ai_connect_admin_portal/package.json
Jira Issue: https://issues.redhat.com/browse/AAP-29418
Bump `axios` version to fix CVE-2024-39338.
n/a
> AAP-29418: CVE-2024-39338 ansible-wisdom-admin-dashboard: axios: Server-Side Request Forgery [services-ansible-wisdom]

- .tekton/ansible-ai-connect-service-pull-request.yaml
- .tekton/ansible-ai-connect-service-push.yaml
The subject ask is deprecated:
https://raw.githubusercontent.com/konflux-ci/build-definitions/main/task/sbom-json-check/0.2/MIGRATION.md
2. ...
3. ...
> remove deprecated sbom-json-check konflux task

- ansible_ai_connect/ai/api/pipelines/completion_stages/pre_process.py
- ansible_ai_connect/ai/api/pipelines/completion_stages/tests/test_pre_process.py
Jira Issue: https://issues.redhat.com/browse/AAP-27481
Stop sending duff multi-task completion requests.
See below.
2. Run `ansible-ai-connect-service` with this PR applied.
3. Run VSCode with [this](https://github.com/ansible/vscode-ansible/pull/1528) PR applied.
4. Enter some multi-task completion requests (see JIRA for examples).
5. Observe the failure messages presented to Users.
As above.
See https://github.com/ansible/vscode-ansible/pull/1528 (however not essential for merge of this PR)
> AAP-27481: Lightspeed Service to prevent users from submitting invalid multitask requests

- ansible_ai_connect/users/reports/generators.py
- ansible_ai_connect/users/reports/tests/test_generators.py
Add:
- Org id
- Org has_api_key
- User UUID
- Trial end (date)
> AAP-30371: user reports: add extra columns

- ansible_ai_connect/users/reports/generators.py
- ansible_ai_connect/users/reports/tests/test_generators.py
Move the `Org has_api_key` column to the last position.
> reports: move position of "Org has_api_key" column

- .snyk
- ansible_ai_connect_admin_portal/package-lock.json
Jira Issue: https://issues.redhat.com/browse/AAP-30888
This PR bumps `body-parser` to `1.20.3` (the fixed version).
It was achieved by running `npm audit fix` that also resolved other issues.
Re-compiled the webapp.
Ran locally and verified operation.
1. Pull down the PR`
2. `cd ./ansible_ai_connect_admin_portal`
3. `npm install`
4. `cd ..`
5. `make admin-portal-bundle`
6. `make start-backends`
7. `make create-application`
8. Run server
9. Login with a User that has Admin permissions
10. Navigate to "Admin Portal".
As above.
> AAP-30888: CVE-2024-45590 ansible-lightspeed-container: Denial of Service Vulnerability in body-parser [ansible_automation_platform-2.4]

- ansible_ai_connect/users/management/commands/generate_users_trials_reports.py
Rename the reports as requested in AAP-31447.
> AAP-31447: rename the Trial reports

- ansible_ai_connect/users/management/commands/tests/test_generate_users_trials_reports.py
- ansible_ai_connect/users/reports/generators.py
- ansible_ai_connect/users/reports/tests/test_generators.py
Move the "Organization name" column and remove the "Trial expired_at" column.
> AAP-31447: Marketing report

- ansible_ai_connect/ai/api/model_client/base.py
- ansible_ai_connect/ai/api/model_client/dummy_client.py
- ansible_ai_connect/ai/api/model_client/langchain.py
- ansible_ai_connect/ai/api/model_client/tests/test_dummy_client.py
- ansible_ai_connect/ai/api/model_client/tests/test_langchain.py
- ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
- ansible_ai_connect/ai/api/model_client/wca_client.py
- ansible_ai_connect/ai/api/serializers.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
- tools/openapi-schema/ansible-ai-connect-service.yaml
Jira Issue: <https://issues.redhat.com/browse/AAP-32137>
Add model parameter to playbook gen/exp APIs.
2. Run Unit tests
Unit test cases are included.
> Add model parameter to playbook gen/exp APIs

- ansible_ai_connect/ai/api/model_client/bam_client.py
- ansible_ai_connect/ai/api/model_client/http_client.py
- ansible_ai_connect/ai/api/model_client/llamacpp_client.py
- ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
- ansible_ai_connect/ai/api/model_client/wca_client.py
- ansible_ai_connect/main/settings/base.py
Jira Issue: <https://issues.redhat.com/browse/AAP-31270>
2. ...
3. ...
> AAP-31270: Option to disable cert verification of WCA endpoint

- ansible_ai_connect/ai/api/exceptions.py
- ansible_ai_connect/ai/api/serializers.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/urls.py
- ansible_ai_connect/ai/api/views.py
- ansible_ai_connect/main/settings/base.py
- tools/openapi-schema/ansible-ai-connect-service.yaml
Jira Issue: <https://issues.redhat.com/browse/AAP-32365>
Add a new API endpoint (`/api/v0/ai/chat/`) for chatbot support.  It is basically compatible with OLS's `/v1/query` API 
2. Run unit tests (which will be written very soon :-) )
So far unit tests only.
> Add chat API endpoint

- ansible_ai_connect/main/permissions.py
- ansible_ai_connect/main/templates/chatbot/index.html
- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/main/urls.py
- ansible_ai_connect/main/views.py
- ansible_ai_connect/users/templates/users/home.html
- ansible_ai_connect/users/views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-33542>
Add `/chatbot` endpoint, where chatbot UI will be placed.
Unit tests are included.
> Add /chatbot endpoint

- ansible_ai_connect/ai/api/wca/api_key_views.py
- ansible_ai_connect/ai/api/wca/tests/test_api_key_views.py
Remove additional permission to check if it's the cause of the failures.
Local testing suggests it is **not** the culprit but let's check!
> Remove additional permission

- ansible_ai_connect/users/one_click_trial.py
> plan: properly display plan with no expiration date

- .github/workflows/npm_audit_chatbot.yml
- .github/workflows/ui_compile_chatbot.yml
- Makefile
- ansible_ai_connect_chatbot/eslint.config.mjs
- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/App.tsx
- ansible_ai_connect_chatbot/src/ReferencedDocuments/ReferencedDocuments.tsx
- ansible_ai_connect_chatbot/src/types/Message.ts
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-33560>
Enable eslint on chatbot.  This PR also includes the updated chatbot TypeScript source files, whose lint rule violations were corrected.
2. Change directory to `ansible_ai_connect_chatbot`
3. Run
```
npm install
npm run eslint
npm run coverage
```
See above
> Enable eslint on chatbot

- ansible_ai_connect/main/settings/base.py
- ansible_ai_connect/main/settings/tests/test_base.py
Jira Issue: <https://issues.redhat.com/browse/AAP-33711>
Incorrect value in environments variable shouldn't disable the SSL protection.
1. All unit tests are green
Tests are green
> AAP-33711: Enable SSL connection if parameter is not recognized

- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/users/one_click_trial.py
- ansible_ai_connect/users/templates/users/trial.html
- ansible_ai_connect/users/tests/test_views.py
Return a better message with an URL pointing on IBM's Lightspeed website.
> AAP-27258: improve the visual when the Trial has expired

- ansible_ai_connect/main/permissions.py
- ansible_ai_connect/main/tests/test_permissions.py
- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/main/views.py
- ansible_ai_connect/users/templates/users/home.html
- ansible_ai_connect/users/views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-34721>
Allow test users to use chatbot in addition to RH employees so that we can start writing E2E/Performance test cases.
Unit tests are included in the PR
> Allow test users to use chatbot

- ansible_ai_connect/main/settings/base.py
- ansible_ai_connect/main/templates/chatbot/index.html
- ansible_ai_connect/main/tests/test_views.py
- ansible_ai_connect/main/views.py
- ansible_ai_connect_chatbot/index.html
- ansible_ai_connect_chatbot/src/index.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-33903>
Parameterize bot and user names.  For user name, the same logic used in Admin Console is used. If values are not specified, bot name is set to `Ansible AI Virtual Assistant` and user name is set to `User`.
Note: The product logo will be replaced by [AAP-32342](https://issues.redhat.com/browse/AAP-32342) and this PR does not contain that change.
Included unit test and manual test running chatbot from local AI Connect server.
> Parameterize bot and user names

- .github/workflows/pip_audit.yml
```
langchain | 0.3.6 | PYSEC-2024-111 |  | A path traversal....
```
No fix version is available at present.
N/A
> Ignore PYSEC-2024-111 until a fix is available.

- .github/workflows/pip_audit.yml
Ignore `PYSEC-2024-115` until a fix is available.
See https://issues.redhat.com/browse/AAP-35075 where we schedule review (and upgrade).
N/A
N/A
N/A
> Ignore PYSEC-2024-115 until a fix is available.

- ansible_ai_connect/ai/api/model_pipelines/bam/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/bam/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/factory.py
- ansible_ai_connect/ai/api/model_pipelines/grpc/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/grpc/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/registry.py
- ansible_ai_connect/ai/api/model_pipelines/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_onprem.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_saas.py
- ansible_ai_connect/main/settings/base.py
Jira Issue: https://issues.redhat.com/browse/AAP-35261
This is a refactoring to simplify existing code; removing duplications.
N/A. Unit test coverage suffices.
N/A. Unit test coverage suffices.
N/A. Unit test coverage suffices.
> AAP-35261: ModelPipelines: Remove duplicate empty implementations

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Jira Issue: NA
PR to update happy-dom and related package in Ansible AI connect chatbot
2. Run npm audit
3. Critical vulnerability should be 0
NA
> PR to update happy-dom and related package in Ansible AI connect chatbot

- .snyk
Ignore [SNYK-PYTHON-ANSIBLECORE-8349549](https://security.snyk.io/vuln/SNYK-PYTHON-ANSIBLECORE-8349549).  It is on the ansible-core library and only exploitable if someone with root privileges uses the user module with the generate_ssh_key option (disabled  by default) and targets an unprivileged user. We do not use ansible-core in that way in ansible-ai-connect-service.
n/a.  Just make sure CI passes.
n/a
> Ignore SNYK-PYTHON-ANSIBLECORE-8349549

- ansible_ai_connect/ai/api/model_pipelines/bam/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/factory.py
- ansible_ai_connect/ai/api/model_pipelines/grpc/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/registry.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_onprem.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_saas.py
- ansible_ai_connect/ai/api/serializers.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
- tools/openapi-schema/ansible-ai-connect-service.yaml
> AAP-33751: implement role generation API interface

- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
Jira Issue: <https://issues.redhat.com/browse/AAP-33572>
Remove the file attach icon in chatbot message box as we are not going to support it (c.f. [AAP-32341](https://issues.redhat.com/browse/AAP-32341)) anytime soon
A unit test case is included.
> Remove file attach icon in chatbot message box

- .tekton/ansible-ai-connect-service-pull-request.yaml
- .tekton/ansible-ai-connect-service-push.yaml
Fix [a Konflux build failure](https://console.redhat.com/application-pipeline/workspaces/ansible-lightspeed/applications/ansible-ai-connect-service/pipelineruns/ansible-ai-connect-service-on-push-k6zhg).
References:
- [Task ecosystem-cert-preflight-checks](https://konflux.pages.redhat.com/docs/users/faq/steps-troubleshooting.html#_task_ecosystem_cert_preflight_checks)
- [knowledge-base-gpt/.tekton/knowledge-base-gpt-pull-request.yaml](https://github.com/ygalblum/knowledge-base-gpt/blob/88036a306ecb47ad7e26d946dc27e978b194297f/.tekton/knowledge-base-gpt-pull-request.yaml#L30C1-L38C22)
Verify Konflux builds (PR & Push) complete successfully
> Konflux build fix

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-34874>
Add "Clear context" button to Chatbot UI so that users can start a new conversation without reloading the browser window.
Unit test cases are provided.
> Clear context button

- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/Constants.ts
Fix two issues on Verify accuracy footnote on chatbot UI.
1. The image on the panel is not displayed in STAGE environment
2. The "Got it" button is associated with a dummy action.
Issue 1 will be resolved by using the Lightspeed icon:
Issue 2 will be resolved by removing the popup and just close the footnote when the button is clicked.
Unit test case is provided.
> Fix issues on Verify accuracy footnote

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Jira Issue: <https://issues.redhat.com/browse/AAP-34074>
Update PF6 virtual assistant library to its `2.1.0-prerelease.15`, which should include the fix for the issue reported in AAP-34074.
Note: The dev dependency on `dompurify` was added for fixing a unit test issue that started occurring after updating the virtual-assistant library.
Run chatbot from a local AI Connect server.
> Update PF6 virtual-assistant

- ansible_ai_connect/main/settings/base.py
Jira Issue: <https://issues.redhat.com/browse/AAP-35817>
PR to make ANSIBLE_AI_ENABLE_PLAYBOOK_ENDPOINT default to True, as per the discussion
2. ...
3. ...
NA
> PR to make ANSIBLE_AI_ENABLE_PLAYBOOK_ENDPOINT default to True

- ansible_ai_connect/ai/api/model_pipelines/bam/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/grpc/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/registry.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_dummy.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_onprem.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_saas.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
- ansible_ai_connect/main/settings/base.py
Jira Issue: https://issues.redhat.com/browse/AAP-32853
This PR moves the ChatBot handler into the same architecture as other _features_.
N/A This is an _internal_ refactoring. No change in function.
> AAP-32853: Refactor ChatBot service

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Update PatternFly chatbot library to the latest pre-release version (2.1.0-prerelease.20)
Executed unit tests.  Also verified UI was correctly displayed by running the code locally.
> Update PF chatbot library to 2.1.0-prerelease.20

- .github/workflows/pre-commit.yml
Ensure `pre-commit.yml` GHA triggers on changes to webapps.
N/A
> Pre-commit GHA to cover webapps

- ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
Use a dedicated outline sample for the role generation.
> rolegen: improve the outline sampe of the "dummy" pipeline

- ansible_ai_connect_chatbot/src/App.test.tsx
This particular test suite fails CI due to an uncaught error which is particularly tricky to track down.  To unblock unrelated PR's we're going to skip these tests.  This will be re-enabled when https://issues.redhat.com/browse/AAP-37878 is addressed.
CI should run successfully
> Skip problematic chatbot app test suite

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Update PatternFly `chatbot` library from `2.1.0-prerelease.20` to `2.20-prerelease.6`.
Executed chatbot from local server
> Update PF6/chatbot to 2.2.0-prerelease.6

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Jira Issue: <https://issues.redhat.com/browse/AAP-32344>
Update PF6 chatbot to 2.2.0-prerelease.8
Unit tests & regular chatbot operation with a local server started with `npm start`
> Update PF6 chatbot to 2.2.0-prerelease.8

- ansible_ai_connect/ai/api/telemetry/schema1.py
- ansible_ai_connect/ai/api/telemetry/test_schema1.py
- ansible_ai_connect/ai/api/tests/test_views.py
- ansible_ai_connect/ai/api/views.py
Use an object defined in ansible_ai_connect/ai/api/telemetry/schema1.py to prepare the Schema1 payload.
> AAP-30619: migrate PlaybookGeneration to the new Schema1 object

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Upgrade PF6 chatbot library to 2.2.0-prerelease.10
Unit tests & manual tests by running a local AI Connect server.
> Upgrade PF6 chatbot to 2.2.0-prerelease.10

- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Fix Granite 3.1 8B model name (`granite31-8b` --> `granite3-1-8b`)
2. ...
3. ...
Manually tested on my local laptop.
> Correct Granite 3.1 model name

- ansible_ai_connect/ai/api/model_pipelines/pipelines.py
- ansible_ai_connect/ai/api/views.py
Remove a spurious parameter; not needed for the ChatBot pipelines.
N/A
N/A
N/A
> Remove spurious request parameter from ChatBot parameters

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Upgrade PatternFly chatbot library to 2.2.0-prerelease.13
Unit test & manual test with a local server
> Update PF chatbot to 2.2.0-prerelease.13

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
Upgrade PF6 chatbot to 2.2.0-prerelease.17, which contains the changes for https://github.com/patternfly/chatbot/issues/388
Executed unit tests
> Upgrade PF6 chatbot to 2.2.0-prerelease.17

- ansible_ai_connect/ai/api/wca/api_key_views.py
- ansible_ai_connect/ai/api/wca/model_id_views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-29904>
https://issues.redhat.com/browse/AAP-29904 for mode details
Unfortunately, there is no way to do a verification for this. Once it is merged and released we should see the results on prod when the prod promotion automation runs.
> AAP-29904: Prevent the occasional HTTP 429 issue in Wisdom service Sanity tests

- ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
Jira Issue: https://issues.redhat.com/browse/AAP-39792
Small follow up to https://issues.redhat.com/browse/AAP-39792.  I was a bit overzealous with my copying and pasting
1. Unit tests pass
> Clean up dummy role explanation

- .github/workflows/code_coverage.yml
This PR is same as https://github.com/ansible/aap-gateway/pull/717
Fix Github CI check error.  
Run CI after merging this
n/a
> Fix Github CI checks

- .github/workflows/code_coverage.yml
- Makefile
- tools/openapi-schema/ansible-ai-connect-service.json
Jira Issue: https://issues.redhat.com/browse/AAP-39998
For api documentation generate schema in json format as well. issue: 
2. run lightspeed service
3. run "make update-openapi-schema"4. ...
> Generate schema in json format

- ansible_ai_connect/healthcheck/backends.py
> make pyright happy again

- ansible_ai_connect/main/settings/production.py
- ansible_ai_connect/main/settings/tests/test_production.py
- ansible_ai_connect/main/tests/test_views.py
Jira Issue: <https://issues.redhat.com/browse/AAP-39044>
"daphne" to ALLOWED_HOSTS for fixing the issue found after enabled streaming chat.
See https://github.com/ansible/ansible-wisdom-ops/pull/1256 for a reference.
> Add daphne to ALLOWED_HOSTS

- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-41197>
Errors can be sent in the stream returned from the `/streaming_chat` API. So far those errors were not processed. This PR change the behavior to show them in the alert popup as shown in the attached screenshot:
2. Run chatbot unit test in the `/ansible_ai_connect_chatbot` folder with `npm test` command
Unit test + manual test.
> Display errors in stream in alert popup

- pyproject.toml
- requirements-aarch64.txt
- requirements-x86_64.txt
- requirements.in
Jira Issue: https://issues.redhat.com/browse/AAP-40664
add ansible_base to pyproject
> add ansible_base to pyproject

- aap_chatbot/package-lock.json
- aap_chatbot/package.json
- aap_chatbot/src/App.test.tsx
- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect_chatbot/package-lock.json
- ansible_ai_connect_chatbot/package.json
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-40371>
Drop granite-3-8b model from the model list, which is displayed on chatbot UI in debug mode.
This PR also includes fixes of npm audit & lint issues found in CI.
Executed unit test and run a manual test by running vite debug server.
> Drop granite3-8b from chatbot UI debug UI model list

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.scss
- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
Jira Issue: <https://issues.redhat.com/browse/AAP-41008>
PR to update the Chatbot UI removing the display mode from UI
2. Run the Chatbot UI integrated with AAP UI
3. Display mode button should be removed from Chatbot UI and by default the display mode should be in full screen.
NA
> PR to update the Chatbot UI removing the display mode from UI

- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect/ai/api/exceptions.py
- ansible_ai_connect/ai/api/model_pipelines/__init__.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/configuration.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/nop/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/nop/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_factory.py
- ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_healthcheck.py
- ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_dummy.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_factory_onprem.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_healthcheck_dummy.py
- ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_healthcheck_saas.py
- ansible_ai_connect/main/settings/base.py
- ansible_ai_connect/main/settings/types.py
- ansible_ai_connect/main/templates/chatbot/index.html
- ansible_ai_connect/users/views.py
- requirements-aarch64.txt
- requirements-x86_64.txt
- requirements.in
Replaces https://github.com/ansible/ansible-ai-connect-service/pull/1585
Add a `llama-stack` `ModelPipeline` provider supporting streaming Chatbot only.
Trust @TamiTakamiya 
This PR adds support for `llama-stack` but does not provide the necessary middleware.
There is therefore no impact on production.
> llamastack ModelPipeline provider

- aap_chatbot/src/App.test.tsx
- aap_chatbot/src/Constants.ts
- aap_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-41821>
Update disclaimer text. Change codes are:
1. Updated the disclaimer text that is displayed when the chatbot window is opened.
2. Updated the label text that is displayed on the link at the bottom of the chatbot window.
|
Unit test + manual test on local server with AAP-UI integration
> Update disclaimer text

- .tekton/ansible-ai-connect-service-pull-request.yaml
- .tekton/ansible-ai-connect-service-push.yaml
https://issues.redhat.com/browse/KONFLUX-2264
Jira Issue: <https://issues.redhat.com/browse/AAP-42097>
Jira Issue: <https://issues.redhat.com/browse/AAP-42097>
The PR and push pipelines should have the new SAST checks
> AAP-42097: Add shell and unicode sast pipeline tasks

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- aap_chatbot/src/App.test.tsx
- aap_chatbot/src/types/Message.ts
- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect/ai/api/model_pipelines/llamastack/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_pipelines.py
Small UI improvement PoC for agent workflow. Intermediate results are displayed when the workflow is being processed and they are hidden in a collapsed area when the final result is obtained. 
https://github.com/user-attachments/assets/44c8e705-e7b8-44df-8af6-1d3b2fb9040c
Unit test + manual test
> UI improvement for agent workflow

- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
- ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
Move roleGeneration in wca_base to make it available for onPrem users.
> roleGeneration for onPrem users

- .github/workflows/ui_publish_aap_chatbot.yml
- .github/workflows/ui_release_aap_chatbot.yml
Just one small fix to make the GHA test environment to work. Thanks!
> AAP Chatbot: GH Actions fix.

- aap_chatbot/package-lock.json
- aap_chatbot/package.json
Just changing the AAP Chatbot package version to `0.1.1`. As I already published it using my own fork's GH worfklows.
Thanks!
> Release AAP Chatbot UI version 0.1.1.

- aap_chatbot/src/useChatbot/useChatbot.ts
> AAP chatbot - fix linter

- .github/workflows/ui_release_aap_chatbot.yml
Just an small fix for signing the commits when creating the PR for releasing  AAP chatbot.
> AAP chatbot - Sign commits when releasing.

- .tekton/ansible-ai-connect-service-push.yaml
No jira
see this conversation: https://redhat-internal.slack.com/archives/C04G3TZBGHJ/p1744298725638969
We can only test this after the merge unfortunately.
> Fix the push pipeline by updating the newly added SAST checks

- aap_chatbot/src/index.tsx
Jira Issue: <https://issues.redhat.com/browse/AAP-42329>
PR to export lightspeed logos for making it work in AAP UI
2. Install and Build aap_chatbot package, pack it 
3. Take changes from AAP UI [PR](https://github.com/ansible/aap-ui/pull/1360)
4. Install the build aap_chatbot package via npx
5. Run AAP UI, check for chatbot header, and lightspeed logo should appear left of title and should update the logo based on theme updates.
> PR to export lightspeed logos for making it work in AAP UI

- aap_chatbot/package-lock.json
- aap_chatbot/package.json
AAP chatbot - Release version 0.1.3
> AAP chatbot - Release version 0.1.3

- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Add granite-3-2-8b to the model drop-down on chatbot UI in debug mode
Unit test
> Add granite-3-2-8b to the model drop-down on chatbot UI in debug mode

- aap_chatbot/src/useChatbot/useChatbot.test.ts
- aap_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-44411>
PR to fix the testathon new line breaks issue, where the line breaks were appearing as line break literals (\n\n), instead of actual line breaks
2. Install the built package locally on AAP UI
3. Line breaks should appear instead of appearing as string literal.
> PR to fix the testathon new line breaks issue

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- aap_chatbot/src/App.test.tsx
- aap_chatbot/src/index.css
- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/index.css
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-44421>
Hide action icons (ThumbsUp/Down, Copy) while streaming. Even though it does not provide any new functions, message rendering looks smoother. 
2. Run unt tests
Unit + manual tests
> Hide action icons while streaming

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- aap_chatbot/src/useChatbot/useChatbot.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-43962>
PR to fix Chatbot header menu tooltip slipping out of iframe and getting displayed over AAP UI.  Extends the #1636 changes.
2. Run chatbot in AAP-integration env and test manually
Manual test only.  This requires Iframe, but currently our test automation does not run chatbot in an iframe.
> IFrame tooltip fix

- aap_chatbot/package-lock.json
- aap_chatbot/package.json
Release 0.1.4 for aap_chatbot.
> AAP Chatbot: Release 0.1.4.

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.scss
- aap_chatbot/src/App.test.tsx
- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.scss
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Adjust avatar icon size.  This is an update for #1629.
2. Start chatbot and verify by eyes
Manual test only
> Adjust avatar icon size

- aap_chatbot/src/Constants.ts
- ansible_ai_connect_chatbot/src/Constants.ts
Jira Issue: <https://issues.redhat.com/browse/AAP-44494>
PR to update chatbot default prompt for limiting response to 5000 words
2. Run the chatbot in local environment, and ask the chatbot following query: "explain aap to me in no less than 100000 words" 
3. Chatbot stream response should complete its response w/o timeout as mentioned in the bug, also the response should be less than 5000 words, ref: [updated_response](https://paste.opendev.org/show/b62iM72PUbTJkM9BwCe7/), instead of much longer response, that results in timeout coz of broken communication.
Also, I observed that still with current prompt sometimes chatbot still gets confused about AAP being open-source, ref: 
```
AAP is available in two versions: a free, open-source version and a paid subscription …
```
> PR to update chatbot default prompt for limiting response to 5000 words

- aap_chatbot/src/Constants.ts
- ansible_ai_connect_chatbot/src/Constants.ts
Jira Issue: NA
PR to fix spacing and line breaks in Chatbot prompt
2. Update the chatbot-service with adjusted prompt
3. Check for the chatbot response, no change should be there in response, but the spacing and line breaks should be fixed.
NA
> PR to fix spacing and line breaks in Chatbot prompt

- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/Constants.ts
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Port changes added to the AAP-UI version of chatbot under `/aap_chatbot` to the Cloud version under `/ansible_ai_connect_chatbot`.  No changes are made under `/aap_chatbot`.
2. Run unit tests.
Unit tests & manual test with local lightspeed server.
> Port aap_chatbot changes to cloud version

- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Chatbot UI change for Granite 3.3
Add new Granite 3.3 model to the model dropdown of chatbot UI in debug mode.
Unit tests + manual test with local server
> Chatbot UI change for Granite 3.3

- requirements-aarch64.txt
- requirements-x86_64.txt
- requirements.in
Update llama-stack-client to 0.2.7.  Old client fails with the latest llama-stack with a message like:
```
Client version 0.1.7 is not compatible with server version 0.2.7.
```
n/a
> Update llama-stack-client to 0.2.7

- pyproject.toml
Jira Issue: https://issues.redhat.com/browse/AAP-50663
downstream is failing, update pyproject.toml with django-ansible-base 2025.3.7 issue:
> update pyproject.toml with django-ansible-base 2025.3.7

- ansible_ai_connect/main/settings/base.py
downstream is failing, update ANSIBLE_BASE_TEAM_MODEL to None for the moment as it's failing to get the attribute from settings.ANSIBLE_BASE_TEAM_MODEL 
Jira Issue: https://issues.redhat.com/browse/AAP-50663
Generated by: <name of code assistant if applicable>
downstream is failing, update ANSIBLE_BASE_TEAM_MODEL to None for the moment as it's failing to get the attribute from settings.ANSIBLE_BASE_TEAM_MODEL
> update settings with ANSIBLE_BASE_TEAM_MODEL

- aap_chatbot/src/useChatbot/useChatbot.ts
- ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
Jira Issue:  n/a
Assisted-by: n/a
Generated by: n/a
The `data.token` sent in the `tool_call` chunk in streaming chat is currently a string. It may be changed to an object. This is for the preparation for the posible change.  The code works even if the `data.token` is a string/
2. Run Unit test
Unit test + manual test with local server.
> Prepare for objects in tool_call output stream chunk

- ansible_ai_connect/ai/api/views.py
- tools/openapi-schema/ansible-ai-connect-service.json
- tools/openapi-schema/ansible-ai-connect-service.yaml
Properly describe the different endpoints.
> openapi: fix the summary of the content gen endpoints

- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/App.test.tsx
- ansible_ai_connect_chatbot/src/InventoryDocumentationModal/InventoryDocumentationModal.test.tsx
- ansible_ai_connect_chatbot/src/InventoryDocumentationModal/InventoryDocumentationModal.tsx
Jira Issue: https://issues.redhat.com/browse/AAP-49581
Assisted-by: claude code
THE CONTENTS OF THE MODAL ARE AI GENERATED AND IS NOT MEANT TO BE THE FINAL VERSION.  I'll update the content when I have it from product docs.
2. ...
3. ...
> Add inventory generation documentation link and modal to ansible_ai_connect_chatbot header

- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.scss
- aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.scss
- ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
Jira Issue: https://issues.redhat.com/browse/AAP-50249
Assisted-by: claude code
Generated by: N/A
Introduces .ansible-chatbot-alert-outer and .ansible-chatbot-alert-inner classes to center and constrain alert messages in the chatbot UI. Updates the component to render alerts outside the main content area for improved layout and visibility.
2. ...
3. ...
> Add styled container for alert messages in both chatbots which pins the alert to the top of the content

- ansible_ai_connect_chatbot/src/InventoryDocumentationModal/InventoryDocumentationModal.test.tsx
- ansible_ai_connect_chatbot/src/InventoryDocumentationModal/InventoryDocumentationModal.tsx
Jira Issue: https://issues.redhat.com/browse/AAP-51603
Assisted-by: claude code
Generated by: <name of code assistant if applicable>
Updated inventory docs modal with content from the docs team
2. ...
3. ...
> Revise InventoryDocumentationModal content and structure

- ansible_ai_connect/ai/api/model_pipelines/http/configuration.py
- ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_ssl_configuration.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_ssl_pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py
- docs/config/examples/README-ANSIBLE_AI_MODEL_MESH_CONFIG.md
Jira Issue: <https://issues.redhat.com/browse/AAP-50667>
Assisted-by: Cursor IDE
Generated by: Claude sonnet 4 for generating the unit test cases
To use openshift SA cert when provided for SSL verfication for TLS enablement.
NA
TEST 1: Using verify=True (current broken approach)
--------------------------------------------------
FAILED: HTTPSConnectionPool(host='ls-stack-service.wisdom-ls-stack.svc.cluster.local', port=8443): Max retries exceeded with url: /readiness (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
Error type: SSLError
TEST 2: Using verify=CA_cert_path (PR fix)
--------------------------------------------------
SUCCESS: Status 200
Response: …
> To use openshift SA cert when required for SSL verfication for TLS enablement

- README.md
- ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_pipelines.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_ssl_configuration.py
- ansible_ai_connect/ai/api/model_pipelines/http/tests/test_ssl_pipelines.py
- ansible_ai_connect/main/settings/base.py
Jira Issue: <https://issues.redhat.com/browse/AAP-50667>
Test Assisted-by: Cursor IDE
Test Generated by: Sonnet
To introduce environment based cert discovery and also eliminates conditional SSL logic complexity that could be reason of failure when `ca_cert_file` is an empty string or invalid path.
2. Build the container, push the image to quay
3. Use the image to test the operator for communication b/w service and chatbot, and it does communicates using https and port 8321
NA
> To introduce env based cert discovery

- ansible_ai_connect_admin_portal/package-lock.json
- ansible_ai_connect_admin_portal/package.json
Jira Issue: <https://issues.redhat.com/browse/AAP-53732>
Assisted-by: NA
Generated by: NA
To fix axios dos affected version for admin portal, addressing [CVE-2025-58754](https://github.com/axios/axios/security/advisories/GHSA-4hjh-wcwx-xvwj). Patched version `>=1.12.0`. Fixed using `npm audit fix`, so change shouldn't break anything and all should work as expected.
2. Axios version upgraded to `1.12.2`
3. .Check under package-lock.json
NA
> To fix Axios DOS affected version for admin portal
