ansible/ansible-ai-connect-service

ansible_wisdom/ai/api/tests/test_views.py

Reduce the dependency between the configuration to run the tests.

TestCompletionWCAView: don't assume ANSIBLE_AI_MODEL_NAME is set

---

ansible_wisdom/ai/api/serializers.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: <https://issues.redhat.com/browse/AAP-21502>
- Avoid duplicated definition of the fields in both `Meta` and as a field.
- Inherite from the `Metadata` class to provide the `ansibleExtensionVersion` field.
- Bonus point: the `ansibleExtensionVersion` fields are properly documented now.
- unit-tests

serializers: simplify the Pydantic configuration

---

ansible_wisdom/ai/api/model_client/tests/test_wca_client.py
ansible_wisdom/ai/api/model_client/wca_client.py

Jira Issue: https://issues.redhat.com/browse/AAP-25100
This is a follow-up to the changes in https://github.com/ansible/ansible-ai-connect-service/commit/615dec7c38c5b2c4b3384ae0e27d0875b1c0cfe0
We have some test users that don't have an org. They are part of the "Commercial" django group and need to use this fake org to retrieve their WCA configuration. This PR leverages the org_id user property to account for faux commercial users.
2. Run an API test with a faux commercial user
3. Inferences should work again as faux commercial user
Verified with steps above plus unit test that fails without my code change.

faux commercial users use faux commercial org

---

ansible_wisdom/users/admin.py
ansible_wisdom/users/tests/test_admin.py

Jira Issue: https://issues.redhat.com/browse/AAP-25178
Currently we can see a user's UUID in django admin, but don't have a good way to find a user by UUID. This PR makes users searchable by UUID.
2. Start the service
3. Log in as a django admin
4. Search users by UUID
Steps above, plus unit test

make user uuid searchable in django admin

---

pyproject.toml
requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

Jira Issue: https://issues.redhat.com/browse/AAP-23758
This addresses CVE-2024-2410. 
No testing has been completed on this change. We do not currently have an active use case for the gRPC client. No regressions are anticipated due to this minor version change.

bump protobuf to 4.25.3

---

ansible_wisdom/ai/api/formatter.py
ansible_wisdom/ai/api/tests/test_formatter.py

Jira Issue: <https://issues.redhat.com/browse/AAP-25320>
Guarantee  we are filtering out Ansible `Playbook's Task` keywords from the module/collection parsing used for telemetry events payload.
- Tested this PR on top of https://github.com/ansible/ansible-ai-connect-service/pull/1108 , in order to ensure no dependency to `ansible` is declared (just the `ansible-core` one)
- Couldn't find a suitable (pre-computed) `List` object in `ansible-core` that provides all available `Task`'s class (and subclasses) fields available to use, so did a once (`global`) computation to get that list/set
-- Upsides: Dynamic Task fields available. No need for further maintaining once upgrading
-- Downsides: Memoized value (memory consumption). Computation costs once spinning up a pod, in order to memoize the …

AAP-25320: Analytics Telemetry: Filter out playbook keywords from the prediction to guarantee parsing the right module/collection

---

ansible_wisdom/ai/api/model_client/tests/test_wca_client.py
ansible_wisdom/ai/api/model_client/wca_client.py
ansible_wisdom/ai/api/model_client/wca_utils.py
ansible_wisdom/ai/api/tests/test_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-25477
There are WCA requests failing in production with a 404 that don't match ResponseStatusCode404WCABadRequestModelId and fall into generic handling, which does not log enough detail to troubleshoot. This PR adds an additional 404 check that logs the response body. It also adds an extra check in ResponseStatusCode404WCABadRequestModelId to be sure it's json before calling json(), which raises an error if the response is not json.
2. Adjust the prediction_url in BaseWCAClient.infer_from_parameters to something one character off
3. Make a completion request
Confirm the 404 response is nicely logged.
Steps above plus unit tests.

better logging for unrecognized 404 inference

---

ansible_wisdom/main/settings/base.py

As defined in the configuration, `podman-compose` will always define  `DEPLOYMENT_MODE`. However, the environment variable may be empty.
This change ensures we fallback on the value `saas` in such situation.

settings: ensure we fallback on "saas" if DEPLOYMENT_MODE is unset

---

ansible_wisdom/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-22663
Our current telemetry for playbook gen/explanation is similar to our "prediction" event in that it maps to a call to WCA. We'll need to add events similar to our "completion" event that we create from our middleware and capture response status code etc. I prefer to reserve the names "generation" and "explanation" for those future events to match the API, and have renamed the existing events to map to the WCA endpoint names.
N/A

rename telemetry events to represent WCA calls

---

ansible_wisdom/main/middleware.py
ansible_wisdom/main/tests/test_middleware.py

Jira Issue: https://issues.redhat.com/browse/AAP-24828
`content` was still being included in the HTTP response which, in conjunction with Axios's uses of `keepalive` for `TCP` connections caused the intermittent errors reported in the JIRA. Presumably, but hard to confirm categorically, Axios was parsing the HTTP stream for a 204 up to the expected end of the payload keeping the connection alive. On subsequent reads the `content` was first read (lingering on the open stream from the first response) which, since an invalid HTTP wire protocol header raised the exception...  Nice.  
Run the `wisdom-service` from this PR with VSCode.
Perform some completions that can return a 204 (hard to find, so using `ANSIBLE_AI_MODEL_MESH_API_TYPE=wca-dummy` and mis-configuring/not configuring ARI for …

AAP-24828: VS Code plugin gets Parse Error on 204

---

ansible_ai_connect/ai/api/fields.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_serializers.py
ansible_ai_connect/ai/api/tests/test_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-23235
Anonymize context variables before passing onto WCA.
_Locally_ you need to put a break-point in `wca_client.py` on `BaseWCAClient.infer(..)`.
Submit a completion request from VSCode (compiled including the applicable enhancement, see below) with a playbook in VSCode that includes an external variables file (or other mechanism to provide _additional context_). Examine the value of `context` in `BaseWCAClient.infer(..)`. PII fields should be anonymized.
2. `make start-backends`
3. `make create-application`
4. Set a break-point as above.
5. Run service in "debug mode".
6. Run VSCode and use the Ansible `.vsix` attached to JIRA.
7. Configure it to use your local `ansible-ai-connect-service` i.e. Lightspeed URL: …

AAP-23235: Include variable values with enhanced context sent from VSCode

---

ansible_ai_connect/ai/api/formatter.py
ansible_ai_connect/ai/api/pipelines/completion_stages/tests/test_pre_process.py

Jira Issue: https://issues.redhat.com/browse/AAP-20564
Per [Ansible variable precedence](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence), we want vars from enhanced context to be listed after vars contained originally in the playbook. In addition, if we get the contents of vars_files files in the enhanced context, we can remove these files from the vars_files list.  
2. Start the wisdom service 
3. Confirm the three scenarios listed [here](https://issues.redhat.com/browse/AAP-20564?focusedId=24100150&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24100150) all give the same task output
As described above.

Enhanced context processing updates

---

ansible_wisdom_console_react/README.md
ansible_wisdom_console_react/config/paths.js
ansible_wisdom_console_react/package-lock.json

Following completion of the module renaming; this PR fixes the output path for builds of the Admin Portal.

Fix output path for Admin Portal build.

---

ansible_ai_connect/ai/api/tests/test_permissions.py

Ensure we actually get a `WcaDummy` client as expected by mocking the
model with `WisdomAppsBackendMocking`.

tests: properly mock the model in AcceptedTermsPermissionTest

---

ansible_ai_connect/ai/api/pipelines/completion_stages/response.py

Only define the model key when the model is Truthy and avoid the
situation where the model key is set to `None` or `''`, which will
raise the following validation error:
```
'{"model":["This field may not be blank."]}'
```

completion_stages/response: only set model when True

---

ansible_ai_connect/main/settings/base.py

`{docker,podman}-compose` set environment variables defined in the configuration.
Most of them will be empty. Because of the way `getenv()` works, we never actually
get the expected default values.
```
$ MY_VAR="" python3
>>> import os
>>> os.getenv("MY_VAR", "never-used")
''
```
This patch ensures we actually fail back on what was the intended defaults.

settings: fix how default value are set

---

ansible_ai_connect/main/settings/base.py
ansible_ai_connect/users/authz_checker.py
ansible_ai_connect/users/tests/test_authz_checker.py

Increase the timeout for all AMS requests from 0.8 to 2 seconds. This hopefully resolves the recent AMS related test failures.

increase AMS timeout to 2 seconds

---

ansible_ai_connect/ai/api/exceptions.py
ansible_ai_connect/ai/api/model_client/base.py
ansible_ai_connect/ai/api/model_client/dummy_client.py
ansible_ai_connect/ai/api/model_client/exceptions.py
ansible_ai_connect/ai/api/model_client/langchain.py
ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_client/wca_client.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-25893
Include `X-Request-ID` header in the `POST`'s for Playbook generation/explanation.
Also include a check that the response contains the same identifier and raise an exception if not accordingly.
It is not possible to test for real since it requires WCA to fail.
Unit tests emulate such failures.
Unit tests.
VSCode change to support new error code: https://github.com/ansible/vscode-ansible/pull/1414

AAP-25893: Set x-request-id header on playbook explanation/generation endpoints

---

ansible_ai_connect/ai/api/model_client/wca_client.py

Jira Issue: [AAP-25884](https://issues.redhat.com/browse/AAP-25884)
This is the continuation of #1183. Even though #1183 successfully added Prometheus metrics (histogram/counter) on Playbook Generation/Explanation APIs, we realized those APIs are slow and often exceeds 10 secs, which is the upper limit of the last (excl. infinity) bucket of the histogram. We should add more buckets to capture more meaningful metrics.
This PR reuses the default buckets used in the django-prometheus library, which contains additional buckets whose upper limits are `25`, `50`, `75` secs in addition to the existing ones (`0.01`, `0.025`, `0.05`, `0.1`, `0.25`, `0.5`, `0.75`, `1.0`, `2.5`, `5.0`, `7.5` and `10.0`)
No test was done.
n/a
No test was performed.

Add more buckets to Prometheus histgrams for WCA APIs

---

ansible_ai_connect/ai/api/permissions.py
ansible_ai_connect/ai/api/tests/test_permissions.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/ai/api/wca/api_key_views.py
ansible_ai_connect/ai/api/wca/model_id_views.py
ansible_ai_connect/ai/api/wca/tests/test_api_key_views.py
ansible_ai_connect/ai/api/wca/tests/test_model_id_views.py
ansible_ai_connect/main/tests/test_console_views.py
ansible_ai_connect/main/views.py
ansible_ai_connect/users/tests/test_users.py

Jira Issue: <https://issues.redhat.com/browse/AAP-26773>
We don't use the permission anymore since the end of the TechPreview.
SAAS already ignores this permission.

drop the AcceptedTermsPermission permission

---

ansible_ai_connect/main/settings/base.py
ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py

DOCUMENTATION_URL was associated with the Tech Preview which is now done.

home view: Don't use DOCUMENTATION_URL anymore

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

This to address the following recent security issues:
```
django | 4.2.11 | PYSEC-2024-58 | 4.2.14,5.0.7 | An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the django.core.files.storage.Storage base class, when they override generate_filename() without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a save() call. (Built-in Storage sub-classes are unaffected.)
django | 4.2.11 | PYSEC-2024-57 | 4.2.14,5.0.7 | An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via …
```

requirements: upgrade Django to 4.2.14

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/healthcheck/tests/test_healthcheck.py
ansible_ai_connect/healthcheck/views.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/tests/test_middleware.py
ansible_ai_connect/main/tests/test_settings.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: https://issues.redhat.com/browse/AAP-24704
Reverts default value for ANSIBLE_AI_MODEL_MESH_MODEL_ID. When this env var is set, we no longer retrieve the model id from secrets manager, which breaks us when deploying in SaaS mode. This PR also removes model_name from the status endpoint since it is not useful in its current form.
2. Run the wisdom service in SaaS mode
3. Run a polaybook generation
4. Confirm the model id is pulled from secrets manager, not hardcoded to "wisdom"
above

do not default ANSIBLE_AI_MODEL_MESH_MODEL_ID

---

tools/docker-compose/pip-compile.yaml

Ensure we set the SELinux label `container_file_t` on the shared volume.
See: https://docs.podman.io/en/latest/markdown/podman-run.1.html
Similar to what was done with 35e4fbc749a20c330d370239fce0927845c8499e.

pip-compile: set the SELinux context

---

tools/authz/validate_ams.py

Closes: https://github.com/ansible/ansible-ai-connect-service/issues/1197
The current regexes will more hosts than intended; example:

limit hosts matched by regex

---

ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/urls.py
ansible_ai_connect/users/templates/users/home.html
ansible_ai_connect/users/templates/users/trial.html
ansible_ai_connect/users/templates/users/trial/terms.html
ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-26231>
Landing page for the 90 days Trial.
- Set `ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL` True
- Connect to the service with OIDC user, the Org should not have any key set
- You should be able to accept the T&C and start a Trial period
No API permission changes should be triggered at this stage. Another PR will come for that.

one-click trial landing page

---

ansible_ai_connect/ai/api/permissions.py
ansible_ai_connect/ai/api/tests/test_permissions.py
ansible_ai_connect/ai/api/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-26581>
When the user's org is not configured yet, we return a different
error message to let the VSCode extension know the user can apply for
a Trial.
- Switch `ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL` to `True`
- Connect with a user with a valid Org but no secret
- Call the API, you should get the `permission_denied__can_apply_for_trial` error code :partying_face:

return permission_denied__can_apply_for_trial for trial candidate

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/tests/test_feature_flags.py
ansible_ai_connect/main/tests/test_console_views.py
ansible_ai_connect/main/tests/test_middleware.py
ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/users/tests/test_throttling.py
ansible_ai_connect/users/tests/test_users.py
ansible_ai_connect/users/tests/test_views.py

The change breaks the `ANSIBLE_AI_ENABLE_TECH_PREVIEW=True` dependency in `test_middleware.py` and also introduces `WisdomServiceAPITestCaseBaseOIDC` which is `WisdomServiceAPITestCaseBase` with an OIDC user. This is a more realistic scenario and the new class should supersede the old one.

test_middleware: remove ANSIBLE_AI_ENABLE_TECH_PREVIEW=True

---

ansible_ai_connect/ai/api/tests/test_serializers.py
ansible_ai_connect/ai/api/utils/seated_users_allow_list.py
ansible_ai_connect/ai/api/utils/tests/test_segment.py

Jira Issue: https://issues.redhat.com/browse/AAP-20367
Allows collection of inlineSuggestionFeedback for licensed users who have not opted out of analytics telemetry.
2. Test an inlineSuggestionFeedback as a user in a not opted out org
3. inlineSuggestionFeedback flows to Segment
4. Test an inlineSuggestionFeedback as a user in an opted out org
5. Request fails with a 400
As described above. Also, there were already existing unit tests to confirm the serializer enforces inlineSuggestionFeedback not being available to users in opted out orgs, so nothing additional to add.

unredact inlineSuggestionFeedback for opted in orgs

---

ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_client/wca_client.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/users/tests/test_authz_checker.py

Jira Issue: n/a. This is for getting more info for [wca-feedback issue#62](https://github.com/rh-ibm-synergy/wca-feedback/issues/62)
Add exception log when exceptions are thrown while WCA API is processed. The backoff tool provided the retry mechanism, but we have not logged those exceptions and did not have detailed information on them.
Unit test cases are provided with the PR.  In addition to test cases and log level setting for WCA API, changes for AMS API (log level setting and test cases) are also provided.
See above.

Add backoff exception logs to wca_client

---

ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/main/urls.py
ansible_ai_connect/users/views.py

Jira Issue: [<https://issues.redhat.com/browse/AAP-26233>]
This PR creates the `/me/summary` API endpoint exposing markdown user information which can be used to populate user information HTML views in the Ansible VS Code extension.
2. Start the service
3. Navigate to [http://localhost:8000/api/v0/me/summary/](url) to view markdown user information

AAP 26233 - expose /me endpoint as markdown

---

ansible_ai_connect/ai/api/exceptions.py
ansible_ai_connect/ai/api/model_client/exceptions.py
ansible_ai_connect/ai/api/model_client/wca_utils.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-27339
Add support for WCA HAP rejections to completions, playbook generation and playbook explanation.
2. Run the service locally
3. Point VSCode at it.
4. Enable Playbook generation.
5. Type something naughty.
As above.
VSCode changes: https://github.com/ansible/vscode-ansible/pull/1432

AAP-27339: Handle HAP detected in playbook gen and explanation

---

ansible_ai_connect/ai/api/wca/model_id_views.py
ansible_ai_connect/ai/api/wca/tests/test_model_id_views.py

**=== REPLACES #1221 WITH CORRECT BRANCH NAME ===**
Jira Issue: https://issues.redhat.com/browse/AAP-27482
Currently HTTP204's from WCA are mapped to HTTP503 in validation of the `model_id`. However in these scenarios the `model_id` was found (otherwise we get other exceptions) it just returned an empty response for the `prompt` we [use](https://github.com/ansible/ansible-ai-connect-service/blob/main/ansible_ai_connect/ai/api/wca/model_id_views.py#L213-L215) to validate `model_id`'s.
This is difficult to test for real; as it needs a model on WCA that, whilst valid, returns HTTP204 for the validation prompt.
2. Unit tests only.

AAP-27482: Lightspeed admin portal saving custom model-ID return 503

---

ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-27650
Admins should not be redirected to the trial page

removing redirect to trial when admin

---

ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/telemetry/test_schema1.py
ansible_ai_connect/ai/api/utils/seated_users_allow_list.py
ansible_ai_connect/ai/api/utils/segment.py
ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-27313>
Send a `newTrial` event when the user accepts the Trial period.
- Add a `print()` at the top of `ansible_ai_connect.ai.api.utils.segment.base_send_segment_event` to trace the payload we will send, or do something more elegant.
- Enable the Trial with `ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL=True`
- Enable the Schema1 event transmission with `SEGMENT_WRITE_KEY=whatever`
- Use an OIDC/RHSSO account with an AAP subscript but without any IBM api key
- Connect to the dashboard
- Accept the Trial period
- Check the logs

trial: send schema1 event after new subscription

---

ansible_ai_connect/ai/api/permissions.py
ansible_ai_connect/ai/api/tests/test_permissions.py

Once the Trials are started, we don't pause them if the `ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL`
value change.

don't pause trial if we disable ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL

---

ansible_ai_connect/users/templates/users/trial.html

Use a dedicated `<div />` to hold the "Your trial period has expired" message.

trial: properly wrap in a <div/> the expiration message

---

.github/workflows/code_coverage.yml
.github/workflows/pip_audit.yml
requirements-aarch64.txt
requirements-dev-aarch64.txt
requirements-dev-x86_64.txt
requirements-dev.in
requirements-x86_64.txt
requirements.in
tools/scripts/pip-compile.sh

Jira Issue: https://issues.redhat.com/browse/AAP-27719
Use Red Hat fork of `certifi` that is hard coded to work with RHEL Certificate Authority store. The `ansible-ai-connect-service` container image is based on `registry.access.redhat.com/ubi9/ubi` which uses different CA store location to other OS's.
N/A

AAP-27719: Lightspeed on-prem using self-signed cert to connect to WCA-onprem failed

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/tests/test_feature_flags.py
ansible_ai_connect/main/tests/test_console_views.py
ansible_ai_connect/main/tests/test_middleware.py
ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/test_utils.py
ansible_ai_connect/users/tests/test_throttling.py
ansible_ai_connect/users/tests/test_users.py
ansible_ai_connect/users/tests/test_views.py

Move:
- create_user
- WisdomServiceAPITestCaseBase
- WisdomServiceAPITestCaseBaseOIDC
At the root level in `ansible_ai_connect.test_utils` to simplify the reusablity.

tests: move user creation function/class at the root level

---

ansible_ai_connect/ai/api/aws/wca_secret_manager.py
ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_client/wca_client.py

For the case the Org admin set-up the WCA key after the Trial begin, we
use the new WCA key.

AAP-28143: Trial users should use Org key is configurated

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

This to address the following CVE:
- CVE-2024-41989
- CVE-2024-41990
- CVE-2024-41991
- CVE-2024-42005
release note: https://docs.djangoproject.com/en/5.0/releases/4.2.15/

requirements: upgrade Django to 4.2.15

---

ansible_ai_connect/organizations/models.py
ansible_ai_connect/organizations/tests/test_organizations.py

From: https://docs.python.org/3/library/unittest.html
```
Changed in version 3.11: unittest dropped the namespace packages support in Python 3.11.
It has been broken since Python 3.7. Start directory and subdirectories containing tests
must be regular package that have __init__.py file.
```
Also fix the `TestOrganization` test failures that are caused by the lazy import.

unittest: add two missing __init__.py files

---

ansible_ai_connect/main/urls.py
ansible_ai_connect/organizations/models.py
ansible_ai_connect/organizations/serializers.py
ansible_ai_connect/users/authz_checker.py
ansible_ai_connect/users/models.py
ansible_ai_connect/users/permissions.py
ansible_ai_connect/users/serializers.py
ansible_ai_connect/users/tests/test_authz_checker.py
ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Expose a new end-points to list (`/api/v0/users`) and retrieve user information (`/api/v0/users/<PK>`) (e.g `/api/v0/users/1`).
To be able to access the end-point, the user needs to be part of a group with the following permissions:
- `view_user`
-  `view_userplan`
- `view_organization`
This explains how to prepare your user:
```python
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
User = get_user_model()
me = User.objects.get(username="gleboude1@redhat.com")
from django.contrib.auth.models import Permission
wisdom_view_users, _ = Group.objects.get_or_create(name="wisdom_view_users")
wisdom_view_users.permissions.add(Permission.objects.get(codename='view_user'))
wisdom_view_users.permissions.add(Permission.objects.get(codename='view_ …
```

AAP-26787: API: add a endpoint to list the users

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

https://github.com/ansible/ansible-ai-connect-service/actions/runs/10388714202/job/28764972767?pr=1255
https://security.snyk.io/vuln/SNYK-PYTHON-AIOHTTP-7675597
> Issues to fix by upgrading dependencies:
>
>  Upgrade aiohttp@3.9.4 to aiohttp@3.10.2 to fix
>  ✗ UNIX Symbolic Link (Symlink) Following (new) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-AIOHTTP-> 7675597] in aiohttp@3.9.4
>    introduced by aiohttp@3.9.4 and 3 other path(s)

Upgrade aiohttp version.

---

ansible_ai_connect/main/exception_handler.py
ansible_ai_connect/main/urls.py
ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/tests/test_views_reports.py
ansible_ai_connect/users/views.py
ansible_ai_connect/users/views_reports.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: https://issues.redhat.com/browse/AAP-26787
This PR adds two CSV reports to `ansible-ai-connect-service` relating to "One Click"/"Trial" work.
2. Ensure `ANSIBLE_AI_ENABLE_ONE_CLICK_TRIAL=True` 
3. Start `ansible-ai-connect-service` locally
4. Login with a User that belongs to an Organisation that does not have a WCA setup (e.g your normal RH login) 
5. You should be prompted to start a trial.
6. Setup a Django Group following the instructions [here](https://github.com/ansible/ansible-ai-connect-service/pull/1251).
This can also be achieved by accessing the Django Admin Console.
- Create a Group
- Add the following permissions to the Group:
- `organizations | organization | Can view organization`
- `users | user | Can view user`
- `users | user plan | Can …

AAP-26787: Extract information about the recent new Lightspeed Trial subscription

---

ansible_ai_connect/users/templates/users/trial.html

Jira Issue: <https://issues.redhat.com/browse/AAP-29473>
[AAP-28829](https://issues.redhat.com/browse/AAP-28829) removed the log out button from the Trial page, but the change caused test failures because our login tests depends on the button. This PR is for restoring the log out button on the Trial page.
Manually click the log out button to make sure it works.
2. Run local service
3. Trigger One Click feature from VS Code extension
4. Click the log out button to ensure it works
See above.

Restore the log out button

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

This PR does not need a corresponding Jira item. -->
```
Issues to fix by upgrading dependencies:
Upgrade cryptography@42.0.6 to cryptography@42.0.8 to fix
✗ Uncontrolled Resource Consumption [Low Severity][https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6913422] in cryptography@42.0.6
introduced by cryptography@42.0.6 and 10 other path(s)
```

Upgrade cyrptography to 42.0.8

---

wisdom-service.Containerfile

Call `npx update-browserslist-db@latest` to avoid a failure later during the `npm run build` if the browser DB is outdated.
```
[1/2] STEP 33/47: RUN npm --prefix /tmp/ansible_ai_connect_admin_portal run build
> admin-portal@0.1.0 build
> node scripts/build.js
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

container: refresh browserslist

---

ansible_ai_connect/ai/api/exceptions.py
ansible_ai_connect/ai/api/model_client/exceptions.py
ansible_ai_connect/ai/api/model_client/wca_utils.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-29861
Handle WCA responses for when the WCA instance on which a model is associated has been deleted.
Unit tests. There's nothing we can test interactively without mocking WCA's responses which is what the unit tests do.
- [PR for VSCode](https://github.com/ansible/vscode-ansible/pull/1519)

AAP-29861: WCA: Handle 'HTTP404: Failed to get remaining capacity' response

---

ansible_ai_connect/users/management/commands/generate_users_trials_reports.py
ansible_ai_connect/users/management/commands/tests/test_generate_users_trials_reports.py

Jira Issue: https://issues.redhat.com/browse/AAP-29990
This PR fixes the handling of date arguments.
See below.
2. Start `ansible-ai-connect-service`
3. Create a Trial Plan for a user (login with an appropriate account and accept trial terms)
4. Start a new Python Run/Debug configuration (in IntelliJ).
5. Set "Script path" to `<path-to->/ansible-ai-connect-service/ansible_ai_connect/manage.py`
6. Set "Parameters" to `generate_users_trials_reports --created-after=2024-08-01`
7. Run it.
8. Try with `--created-before` argument too.
As above.

AAP-29990: User Trials Reports: Date argument handling

---

ansible_ai_connect/users/management/commands/generate_users_trials_reports.py
ansible_ai_connect/users/management/commands/tests/test_generate_users_trials_reports.py
ansible_ai_connect/users/reports/generators.py
ansible_ai_connect/users/reports/tests/test_generators.py

Jira Issue: https://issues.redhat.com/browse/AAP-29990
Further to #1272 this PR adds timezone support.
See below.
2. Start `ansible-ai-connect-service`
3. Create a Trial Plan for a user (login with an appropriate account and accept trial terms)
4. Start a new Python Run/Debug configuration (in IntelliJ).
5. Set "Script path" to `<path-to->/ansible-ai-connect-service/ansible_ai_connect/manage.py`
6. Set "Parameters" to `generate_users_trials_reports --created-after=2024-08-01`
7. Run it.
8. Try with `--created-before` argument too.
As above.

AAP-29990: User Trials Reports: Date argument handling. Add TimeZone information

---

ansible_ai_connect/test_utils.py
ansible_ai_connect/users/management/commands/migrate_email_name_from_ams.py
ansible_ai_connect/users/management/commands/tests/test_migrate_email_name_from_ams.py
ansible_ai_connect/users/reports/generators.py
ansible_ai_connect/users/reports/tests/test_generators.py
ansible_ai_connect/users/serializers.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: <https://issues.redhat.com/browse/AAP-30180>
Initialize the RHSSO users's email/given_name/family_name from AMS.
Run `wisdom-manage migrate_email_name_from_ams`.
- :warning:  This code change requires the following considerations before going to production:
We need to manually run `wisdom-manage migrate_email_name_from_ams` in the secondary environment first.

AAP-30180: trial report, get email/name from RHSSO

---

README.md
requirements.in

Add a note reminding us to keep `pyproject.toml` synchronised with `requirements.in`
n/a

Add note to remind us to keep pyproject.toml synchronized.

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

This to address the following CVE:
- CVE-2024-45230
- CVE-2024-45231
See: https://docs.djangoproject.com/en/5.1/releases/4.2.16/

requirements: upgrade to Django==4.2.16

---

wisdom-service.Containerfile

Call `npx update-browserslist-db@latest` during the container build. This
to address the following error:
```
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

Containerfile: call npx update-browserslist-db during the build

---

tools/docker-compose/pip-compile.yaml

Avoid triggering the two builds at the same time. This leads to a race condition
during the build on my local set-up.

pip-compile: do a sequential run

---

ansible_ai_connect/ai/api/model_client/wca_utils.py

Use the new and more specific error message from WCA to identify a delete WCA instance.
See: https://github.com/rh-ibm-synergy/wca-feedback/issues/63

AAP-30596: improve the WcaInstanceDeleted check

---

ansible_ai_connect/users/reports/postman.py

The message itself is actually in the `body` attribute.
See: https://slack.dev/python-slack-sdk/api-docs/slack_sdk/webhook/webhook_response.html#slack_sdk.webhook.webhook_response.WebhookResponse

postman/slack: print the actual error message

---

ansible_ai_connect/users/auth.py
ansible_ai_connect/users/tests/test_auth.py

Jira Issue: <https://issues.redhat.com/browse/AAP-25344>
Fixed links for AAP 2.5 Gateway API. Now it supports both AAP Controller and AAP Gateway.
2. Ran in on-prem mode
3. Configure AAP 2.5 Gateway
4. Log in into Lightspeed using AAP Gateway
5. Configure AAP 2.4/2.5 Controller
6. Log in into Lightspeed using AAP Controller
Described above (used AAP 2.5 Gateway and Controller)

AAP-25344: AAP 2.5 Gateway SSO for Lightspeed

---

ansible_ai_connect/users/reports/postman.py
ansible_ai_connect/users/reports/tests/test_postman.py

Use the data BEFORE the `created_after` parameter to build the report file name.

AAP-31447: build the filename from the day before created_before

---

ansible_ai_connect/ai/api/model_client/base.py
ansible_ai_connect/ai/api/model_client/dummy_client.py
ansible_ai_connect/ai/api/model_client/langchain.py
ansible_ai_connect/ai/api/model_client/tests/test_langchain.py
ansible_ai_connect/ai/api/model_client/wca_client.py
ansible_ai_connect/ai/api/pipelines/completion_stages/pre_process.py
ansible_ai_connect/ai/api/pipelines/completion_stages/tests/test_pre_process.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/main/exception_handler.py
ansible_ai_connect/test_utils.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: https://issues.redhat.com/browse/AAP-30426
Support `customPrompt` JSON field for both Playbook Generation and Explanation.
**_Playbook Generation_**
- The backend expects `{goal}` or both `{goal}` and `{outline}` keywords to be present in the `custom_prompt`
- Depending on if Goal or both Goal and Outline are provided
**_Playbook Explanation_**
- The backend expects `{playbook}` keyword to be present in the `custom_prompt`
2. `make start-backends`
3. `make create-application`
4. Run server
5. Create User API token:
- Login into Lightspeed as somebody
- Login to `http://localhost:8000/admin` as Django admin
- Create an Access Token for the User you logged into Lightspeed as
6. Run **generation** tests:
- Valid "custom prompt"
```
curl -X 'POST' \ …
```

AAP-30426: Lightspeed API playbook generation and explanation to accept a new custom_prompt field

---

.pre-commit-config.yaml
ansible_ai_connect/ai/api/telemetry/schema2.py
ansible_ai_connect/ai/api/telemetry/schema2_utils.py
ansible_ai_connect/ai/api/telemetry/tests/test_schema2.py
ansible_ai_connect/ai/api/utils/segment_analytics_telemetry.py
ansible_ai_connect/ai/api/utils/tests/test_segment_analytics_telemetry.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/main/middleware.py
ansible_ai_connect/users/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-31593>
- Adding `OneClickTrialStarted` for `schema2`telemetry
- Refactoring some `schema2` stuff into `telemetry` package
- `OneClickTrialStarted` event definition => Given the actual use cases (see [AAP-31593](https://issues.redhat.com/browse/AAP-31593)), notice I don't send the `accept_marketing` field for `schema2`, as we already do for `schema1`, and I understand that's not for the use case of telesense team. Other fields' are preserved. Let me know if you think it should be preserved otherwise.
Thanks!
Tested locally against our wisdom staging Segment's  account. Events are flowing.
2. Run the service
3. Start a trial
4. Look at Segment, if the `OneClickTrialStarted` has been sent, as expected.

AAP-31593: One click Trial - schema2 telemetry enablement.

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

```
Issues to fix by upgrading dependencies:
Upgrade jsonpickle@3.0.4 to jsonpickle@3.3.0 to fix
✗ Arbitrary Code Execution (new) [Critical Severity][https://security.snyk.io/vuln/SNYK-PYTHON-JSONPICKLE-8136229] in jsonpickle@3.0.4
introduced by jsonpickle@3.0.4 and 1 other path(s)
```

Upgrade jsonpickle to 3.3.0

---

ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_client/wca_client.py

Jira Issue: https://issues.redhat.com/browse/AAP-32524
This PR ensures `custom_prompts` end with a `\n` character.
2. Start `ansible-ai-connect-service`
3. Run the "special" VSCode extension, supporting "custom prompts".
4. Verify you receive "Playbook generation" responses.
As above.

AAP-32524: Lightspeed: Playbook generation: Custom prompt must end with \n

---

ansible_ai_connect/ai/api/model_client/base.py
ansible_ai_connect/ai/api/model_client/dummy_client.py
ansible_ai_connect/ai/api/model_client/langchain.py
ansible_ai_connect/ai/api/model_client/tests/test_dummy_client.py
ansible_ai_connect/ai/api/model_client/tests/test_langchain.py
ansible_ai_connect/ai/api/model_client/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_client/wca_client.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: https://issues.redhat.com/browse/AAP-32403
Ensure `warnings` returned from WCA are included in the API response payload.
2. Unit tests
Unit tests.

AAP-32403: Lightspeed: Playbook generation: Handle "warnings" in response

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-32365>
This is a bug found in #1334.  Before assigning `conversation_id` in a JSON, the value (a UUID) needs to be converted into a string.
A modification to a subroutine used in Chat API unit tests is provided. Manual tests were also performed using the chatbot PoC.

A UUID value cannot be in JSON

---

ansible_ai_connect/users/views.py

If an Anonymous hits /trial, we now redirect it to the Login page. This will
be enough to avoid the err 500.

AAP-29291: Trial: redirect Anonymous used to the login page

---

ansible_ai_connect/ai/api/model_pipelines/bam/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/factory.py
ansible_ai_connect/ai/api/model_pipelines/grpc/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/wca/api_key_views.py
ansible_ai_connect/ai/api/wca/tests/test_api_key_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-32268
Following #1343 this PR fixes an issues with use of `cast(..)` and adds licences to new files.
The failure was spotted during execution of our [CI pipeline](https://github.com/ansible/ansible-wisdom-testing/actions/runs/11372520531/job/31637023512).
N/A
N/A
N/A

AAP-32268: Refactor ModelMeshClient into single responsibility. Fix casts. Add licenses.

---

ansible_ai_connect/ai/api/wca/api_key_views.py
ansible_ai_connect/ai/api/wca/tests/test_api_key_views.py

Revert https://github.com/ansible/ansible-ai-connect-service/pull/1350
This reverts commit `b4091a4ccf546a60e560b989d21a4e9050536e6c`.
Removal of the additional permission did not solve the problem.. which must lay elsewhere....

Revert "Remove additional permission"

---

ansible_ai_connect/ai/api/model_pipelines/bam/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/grpc/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_bam_client.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_dummy_client.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_langchain.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_llamacpp_client.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_ollama_client.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_api_timeout.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/main/tests/test_middleware.py

Jira Issue: https://issues.redhat.com/browse/AAP-33632
Refactoring away of explicit `infer(..)`, `codematch(..)`, `generate_playbook(..)` and `explain_playbook(..)` methods.
A single `invoke(..)` method exists on a given _pipeline_. The parameters for each _feature_ differ.
N/A Refactoring exercise.
2. Run Wisdom Service locally
3. Connect with VSCode
4. Check things stil work
As above

AAP-33632: ModelPipelines: Implement invoke(..) method

---

ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Introduce the `AACSAPIView` class to handle the generic parts of the view. For now, we use it only for the `Explanation` view and it will be extended to the other views later.
The class is in charge of:
- the Schema1 event creation and emission
- the exception handling
- the parameter handling (not in this PR, stay turned!)

AAP-30617: Introduce AACSAPIView to handle the generic aspect of the view

---

ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/telemetry/test_schema1.py

All the events based on `Schema1Event` have now the `duration` and the `timestamp` fields set.

schema1: set duration and timestamp by default

---

ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-32080>
Updates test cases based on the comments I got for #1326. Except for one line to add a log at DEBUG level, all changes are in test codes.
2. Run test cases
This is a PR on test cases.

Update test cases for AAP-32080

---

.github/workflows/code_coverage.yml
.github/workflows/npm_audit.yml
.github/workflows/npm_audit_chatbot.yml
.github/workflows/ui_compile.yml
.github/workflows/ui_compile_chatbot.yml

Jira Issue: related to https://issues.redhat.com/browse/AAP-31381
PR to update node version to 21.x from existing 20.x. This is to fix the CVE around serialize-javascript, please ref the https://github.com/ansible/ansible-ai-connect-service/pull/1353#issuecomment-2429222264
2. Install node 21.x in your machine
3. Run `npm install`, and the [CI failure](https://github.com/ansible/ansible-ai-connect-service/actions/runs/11459341065/job/31883616193?pr=1353#step:4:22) observed here should not be observable with the upgraded node.
NA

PR to upgrade node from 20.x to 21.x

---

ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/settings/development.py

Jira Issue: https://issues.redhat.com/browse/AAP-32019
This PR adds support for Playbook Generation and Explanation for "on prem".
It is enabled/disabled with the environment variable `ENABLE_PLAYBOOK_ENDPOINT`
See JIRA for instructions.
See JIRA for instructions.
As above.
This PR depends on https://github.com/ansible/ansible-wisdom-ops/pull/1096

AAP-32019: Enable Playbook generation/explanation endpoint in Lightspeed service for on-prem

---

.github/workflows/pip_audit.yml

```
langchain | 0.3.6 | GHSA-hc5w-c9f8-9cc4 |  | A path traversal vulnerability exists in the `getFullPath` ....
```
See https://issues.redhat.com/browse/AAP-35075 for details.
N/A
N/A
N/A

Ignore GHSA-hc5w-c9f8-9cc4 until the CVE is corrected for the Python library

---

ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-35211>
Add a timestamp to each message when it is received. Othewise, timestamps are dynamically generated at runtime and vary at every re-draw.
2. Run the chatbot locally and see message timestamps stay in fixed values.

Set chatbot message timestamp when a message is received

---

.github/workflows/pip_audit.yml

The problem happens only if the `ansible.builtin.user` module is used,
which is not our case. We never call any ansible commands.
See: https://github.com/advisories/GHSA-32p4-gm2c-wmch

pip-audit: ignore GHSA-32p4-gm2c-wmch

---

ansible_ai_connect/ai/api/formatter.py
ansible_ai_connect/ai/api/tests/test_formatter.py

Jira Issue: <https://issues.redhat.com/browse/AAP-34871>
Please see Jira Issue: <https://issues.redhat.com/browse/AAP-34871> and
see https://github.com/rh-ibm-synergy/wca-feedback/issues/129
2. Run the wisdom service on your local and connect it to your vscode.
3.  Create a YAML playbook file on your local with the following content:
```
---
- name: Deploy simple website using Ansible Lightspeed with watsonx Code Assistant
hosts: all
gather_facts: false
become: true
tasks:
- name: Ensure httpd package is installed
ansible.builtin.package:
name: httpd
state: present
- name: Configure httpd on port 8083
ansible.builtin.copy:
content: <h1>Hello world from AWS</h1>
dest: /var/www/html/index.html
```
4.  After saving the playbook, go to the end of the line " # Start and …

AAP-34871: Tasks in wrong order

---

ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: NA
PR to update chatbot disclaimer, as specified in new mockup
2. npm install
3. npm run start

PR to update chatbot disclaimer

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/templates/chatbot/index.html
ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/main/views.py
ansible_ai_connect_chatbot/index.html
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/types/Model.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-35616>
Enable "debug" chatbot UI that allows end-user to pick up a model to be used. This time it only allows to use the default `granite-8b` model and the `granite3-8b` model, which was installed with AAP-35616,
This is enabled only when the chatbot UI is loaded with `?debug=true` query parameter, e.g.
https://stage.ai.ansible.redhat.com/chatbot?debug=true
Unit tests are included

Chatbot debug mode

---

ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-35725>
Set API timeout to 28 secs and display an error message `Chatbot service is taking too long to respond to your query. Try to submit a different query or try again later.` in the chat window instead of showing an alert with a 504 error.
A unit test case is included

Chatbot timeout message

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

```
aiohttp | 3.10.2 | GHSA-8495-4g3g-x7pr | 3.10.11 | ### Summary The Python parser parses newlines in chunk extensions incorrectly which can lead to request smuggling vulnerabilities under certain conditions.
```

Upgrade aiohttp to 3.10.11

---

ansible_ai_connect/ai/api/model_pipelines/wca/configuration_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_configuration_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_configuration_saas.py

Jira Issue: https://issues.redhat.com/browse/AAP-33633
Further to https://github.com/ansible/ansible-ai-connect-service/pull/1389
@TamiTakamiya reported Staging `Pod`'s were failing to start as the `api_key` was missing.
I added `ANSIBLE_AI_MODEL_API_KEY` environment variable to both Staging and Production AWS Secret Manager.
However @ldjebran reported his use of VSCode against Production with the environment variable set was broken.
Reverting `ANSIBLE_AI_MODEL_API_KEY` fixed the problem; meaning `api_key` *should be optional*.
This PR makes `api_key` optional.
Unit Tests.
However the issue was not evident until deployment to Staging was attempted.

AAP-33633: ModelPipelines: Configuration improvements. WCA(-onprem) API Key is optional

---

ansible_ai_connect/healthcheck/backends.py
ansible_ai_connect/healthcheck/tests/test_healthcheck.py

Jira Issue: <https://issues.redhat.com/browse/AAP-35769>
Use the `/readiness` endpoint of chatbot service instead of the `/liveness` for chatbot-service healthcheck, which is performed when AI Connect service's `/check/status` endpoint is invoked.  Since the `/readiness` endpoint of chatbot service checks the statuses of RAG index and LLM, we can use it for monitoring LLM as well.
Unit tests, written by @mabashian are included in the PR.

Use readiness endpoint for chatbot healthcheck

---

ansible_ai_connect/ai/api/exceptions.py
ansible_ai_connect/ai/api/model_pipelines/exceptions.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/wca_utils.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-36462
During testing of `r11` it was noted that WCA sometimes returns `HTTP422`.
IBM explained this is caused by WCA failing to validate the response from the model. A reproducer is included in the JIRA.
This PR adds support for propagating `HTTP422`'s to VSCode where a suitable message can be display.
Run `ansible-ai-connect-service` with this PR.
Run VSCode, with the related PR applied, pointing to your local `ansible-ai-connect-instance`
2. Run `ansible-ai-connect-service` with this PR.
3. Run VSCode, with the related PR applied, pointing to your local `ansible-ai-connect-instance`
4. Try the example playbook (in the JIRA)
5. A _friendly_ message should be displayed.
As above.
Note. There is a VSCode PR too; however …

AAP-36462: [r11]: Add support for HTTP422 response

---

ansible_ai_connect/ai/api/model_pipelines/config_serializers.py
ansible_ai_connect/ai/api/model_pipelines/dummy/configuration.py
ansible_ai_connect/ai/api/model_pipelines/registry.py
ansible_ai_connect/main/settings/base.py

Set a default configuration structure for the "dummy" api type and
adjust the codebase to use Python Comprehensive when possible.

model_pipeline: set a default configuration for "dummy"

---

.pre-commit-config.yaml
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/utils/segment.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: <https://issues.redhat.com/browse/AAP-33570>
Adding support for both feedback an operational events, on `schema1`, for the chatbot. 
NOTE: As commented with Marty, those chatbot telemetry events are **NOT inheriting fields** as in other `schema1` events, such as `hostname`, `groups`, `plans`, `has_seat` etc. Let us know if you see any issue on that. We just want to ensure we don't spend payload on unnecessary stuff.
2. Set the proper `SEGMENT_WRITE_KEY`
3. Run wisdom service and access the chatbot UI
4. Perform any Q -> a new `chatOperationalEvent`event  must be sent
5. Click on thumbs up/down -> a new `chatFeedbackEvent`event  must be sent
Local against chatbot on staging.

Chatbot feedback model and API implementation with Schema 1 telemetry

---

ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/index.css
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-33572>
Sentiment feedback (ThumbsUp/Down) UI implementation
(Unit tests will be provided soon...)

Sentiment feedback

---

ansible_ai_connect_chatbot/README.md
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: NA
PR tp remove chatbot model selector which now defaults to granite3-8b
2. npm install
3. npm run start
4. chatbot model selector is defaulted to 3-8b and 8b is removed from option.
NA

PR tp remove chatbot model selector which now defaults to granite3-8b

---

ansible_ai_connect/main/settings/base.py

A simple internal refactor to rename an environment variable from what is implied WCA usage; to a general form.
N/A

Rename env var used to configure ModelPipelines

---

ansible_ai_connect/ai/api/model_pipelines/bam/configuration.py
ansible_ai_connect/ai/api/model_pipelines/config_pipelines.py
ansible_ai_connect/ai/api/model_pipelines/config_serializers.py
ansible_ai_connect/ai/api/model_pipelines/dummy/configuration.py
ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/grpc/configuration.py
ansible_ai_connect/ai/api/model_pipelines/http/configuration.py
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/configuration.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/configuration.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/nop/configuration.py
ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/configuration.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_saas.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/healthcheck/apps.py
ansible_ai_connect/healthcheck/backends.py
ansible_ai_connect/healthcheck/tests/test_healthcheck.py
ansible_ai_connect/healthcheck/views.py
ansible_ai_connect/main/settings/base.py

Jira Issue: https://issues.redhat.com/browse/AAP-33634
Add/expose "Health Check" for each pipeline.
The "aliases" of "Completions" and "Chat Bot" have been preserved as `model-server` and `chatbot-service` respectfully.
This means we _should not_ have to update our test suites - nor anybody else who depends on the existing names.
Run the service locally and check the _health_ endpoint: http://127.0.0.1:8000/check/status/
Example output:
```
{
"timestamp": "2024-12-06T09:38:32.625598",
"version": "image-tags-not-defined",
"git_commit": "git-commit-hash-not-defined",
"deployed_region": "unknown",
"status": "error",
"dependencies": [
{
"name": "secret-manager",
"status": "ok",
"time_taken": 466.697
},
{
"name": "authorization",
"status": "ok",
"time_taken": 0.032
},
{
"name": "db",
"status": …
```

AAP-33634: ModelPipelines: Health endpoint improvements

---

ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/tests/test_pipeline.py
ansible_ai_connect/main/settings/base.py

Jira Issue: <https://issues.redhat.com/browse/AAP-34739>
2. Ran locally with Ollama
3. Get token: `python ansible_ai_connect/manage.py createtoken --username admin_test`
4. Run culr request:
```bash
curl -X 'POST' \
'http://127.0.0.1:8000/api/v0/ai/generations/role' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer LlY0NYDDj5fLqmMzsfVkyNuNcreSRS" \
-d '{
"text": "Prepare a VPC, create the subnets, and deploy an ec2-instance",
"createOutline": true,
"generationId": "6abdaa82-a704-4883-9f7b-759b85fc1d9e"
}'
```

AAP-34739: Implement the role generation with the Ollama pipeline

---

ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-37122>
PR to implement copy to clipboard functionality to AAP virtual assistant
2. run npm install
3. change `An unexpected error occured` to 
```
const chatResponse: ChatResponse = {
conversation_id: "1",
response: "this to implement copy to clipboard!!",
referenced_documents: [],
truncated: false
};
const referenced_documents = chatResponse.referenced_documents;
if (!conversationId) {
setConversationId(chatResponse.conversation_id);
}
const newBotMessage: any = botMessage(chatResponse, message);
newBotMessage.referenced_documents = referenced_documents;
addMessage(newBotMessage);
```
and `feedback` exception to:
```
const newBotMessage = {
referenced_documents: [],
...feedbackMessage(feedbackRequest),
};
```
4. run: …

PR to implement copy to clipboard functionality to AAP virtual assistant

---

.tekton/ansible-ai-connect-service-pull-request.yaml

Rely only on the 0.2 tag to get quay.io/redhat-appstudio-tekton-catalog/task-summary.

Tekton: remove the extra SHA256 used to pin task-summary version

---

.github/workflows/pyright.yml
ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_pipelines.py
docs/pycharm-setup.md
requirements-aarch64.txt
requirements-dev-aarch64.txt
requirements-dev-x86_64.txt
requirements-dev.in
requirements-x86_64.txt
requirements.in

The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0.
See: https://github.com/langchain-ai/langchain/commit/95a87291fd821bb02fe1bb0f3e9cb65f3e75e39b

langchain/Ollama: move to langchain_ollama.OllamaLLM

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-37014>
- Make Wisdom's Chatbot interfaces available to RH employees only
- Assume a RH employee when it has the `redhat:employees` realm role and it's email is from `redhat.com` domain
Tested locally against an employee user, and a non-employee user. 
Tested both chatbot view and API endpoint.

AAP-37014: Make Wisdom's Chatbot interfaces available to RH employees only

---

.tekton/ansible-ai-connect-service-push.yaml

See: 404a60e0ba42d9ce93d3a26dec61a9a764946865

konflux: only use the tag to pin quay.io/redhat-appstudio-tekton-catalog/task-summary

---

ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-37349>
**It depends on** https://github.com/ansible/ansible-lightspeed-va-feedback/pull/9
Once creating a GH issue from the chatbot UI's send button (after thumbs down), it also sends to GH issue creation endpoint the query parameter for referenced documents.
Tested locally against the issue template.

AAP-37349: Ansible Chatbot: Collect referenced documents information as well in issues feedback being created from the UI

---

ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Sorry just a small fix that prevents to properly use the feedback button in the chatbot UI.

AAP-37349: ChatBot - Fix using the proper feedback endpoint.

---

ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

This PR attempts to make the ChatBot tests _more stable_.
Ideally it'd fix them completely but that appears to be a Holy Grail that's difficult to reach.
N/A

An attempt to fix ChatBot tests.

---

ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/users/one_click_trial.py
ansible_ai_connect/users/templates/users/trial.html
ansible_ai_connect/users/tests/test_views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-36175>
This updates the messages that we present to the user when a trial will expire in <= 90 days as well as when a trial is expired.
I tested out all of the various scenarios by manipulating the expired_at timestamp on the user plan.  There are 4 options/scenarios:
1. A trial hasn't started yet
2. Expired (date set to something in the past)
3. About to expire (date set to something within the next 90 days)
4. Not about to expire (date set to something more than 90 days out).  Theoretically this shouldn't be possible but it's a scenario we already cover so I tested it anyway.
See above

Update trial messages in both vscode extension and trial web page

---

.github/workflows/code_coverage.yml
ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/package.json
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/setupTests.ts
ansible_ai_connect_chatbot/vite.config.ts

Right now, our tests are failing due to some problem with `happy-dom`, the fake webbrowser
used to run the tests by `react-testing-library`. `jsdom` is an alternative but we cannot
use it without adjusting our tests and facing similar issues or limitations.
By moving to `vitest-browser-react`, we are now able to run the tests against a real browser
like Chrome or Firefox. We still have the option to run the tests "headless" for a CI environment.
`vitest-browser-react` is directly based on `vitest-browser` and allow us to stay in a standard
`vite` ecosystem. It also reuses some elements from `react-testing-library`, which explains why
the PR is not that large.
Overall, this change reduces the differences between our tests and the production environment,
and allow us to limit our exposure …

AAP-37878: move Chatbot test to vitest-browser-react

---

ansible_ai_connect_admin_portal/package-lock.json
ansible_ai_connect_admin_portal/src/__tests__/AppHeader.test.tsx
requirements.in

Jira Issue: https://issues.redhat.com/browse/AAP-36512
Reinstate a test that was removed as part of the miration to PF5.
N/A. This PR contains a reinstated unit test.
N/A. This PR contains a reinstated unit test.
N/A. This PR contains a reinstated unit test.

AAP-36512: FIx Admin portal tests fallout due to PF5 and latest Ansible-UI-framework

---

ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/ColorThemeSwitch/ColorThemeSwitch.tsx

As the `pf-v6-theme-light` CSS class is no longer used in PF6 chatbot, remove it from our `ColorThemeSwitch` class and update its unit test accordingly.
A modification of a unit test case is provided in the PR. Also a manual test was executed using local chatbot instance.

Update ColorThemeSwitch and its unit test

---

ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-35711>
This also will fix the issue reported by https://github.com/ansible/ansible-lightspeed-va-feedback/issues/15
On the existing implementaiton, when a new bot message is received, chatbot window scrolls to the bottom of the message. It is changed to scroll to the top of the last message instead.
Also when a ThumbsUp/Down icon is clicked for a bot message, which is NOT the last one, the feedback message is added to the bottom and chatbot window scrolls to the bottom (it is the issue reported by https://github.com/ansible/ansible-lightspeed-va-feedback/issues/15). With this PR, the feedback message will be added right after the bot message, to which the feedback was sent, and chatbot window scrolls to the top of the feedback message.
1. …

Fix chatbot UI autoscrolling and insert position for bot message feedback

---

ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: <https://issues.redhat.com/browse/AAP-38211>
Add system_prompt to `POST /chat` endpoint.
Unit test cases are included.

Add system_prompt to chat endpoint

---

ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/telemetry/test_schema1.py

Amplitude cannot do a filter that match a single key in an array, if we want to
correctly identify an event's plan(s) we need to flatten the plan_id keys.

schema1: set the new plan_ids keys

---

ansible_ai_connect_chatbot/src/App.test.tsx

See: https://testing-library.com/docs/queries/about/#findby

ansible_ai_connect_chatbot: use findBy* to find dynamic content

---

pyproject.toml

Don't force the use of the `binary` package. It may not be available (e.g Python 3.13 Linux).

pyproject: accept the regular flavor of psycopg

---

ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/urls.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

This way we have:
- `/api/v0/ai/generations/playbook` for playbook generation
and `/api/v0/ai/generations/role` for roles.

expose /generations/playbook to be consistent with roleGen

---

ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/utils/segment.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-33915
Internal refactoring of existing code.
N/A. Internal refactoring of existing code.
N/A. Internal refactoring of existing code.
N/A. Internal refactoring of existing code.

AAP-33915: Use the new exception handler for the Chat view

---

ansible_ai_connect/ai/api/exceptions.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Validate the view parameter from within the `AACSAPIView` class as soon as the `request_serializer_class` attribute is set with a Serializer class.
Also introduce minor cosmetic changes in Serializer class definitions to set some default values.
These changes are optional but the ultimate goal is to ensure all the fields are set in the `validated_data`
structure. This to reduce the use of `.get()`, which can silently hide an actually problem. This is also a way to
ensure the type of the field remains the same.

AACSAPIView: validate the payload in the class

---

ansible_ai_connect/ai/api/model_pipelines/dummy/configuration.py
ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_configuration.py
ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py

Jira Issue: https://issues.redhat.com/browse/AAP-38593
Following feedback from @goneri all of the configuration parameters for `dummy` are optional.
Unit Tests.
Unit Tests.

AAP-38593: ModelPipelines: dummy: All parameters are optional

---

ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-38324>
Implement chat history UI.
Unit tests + manual tests by running a local AI Connect server.

Chat History Frontend-only Implementation

---

ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/utils/seated_users_allow_list.py
ansible_ai_connect/ai/api/utils/segment.py
ansible_ai_connect/ai/api/utils/tests/test_segment.py

Skip "seated user check" for Chat-related segment events because Chat is irrelevant to "seated users" or WCA.
I added two new entries to `allow_list`:
``` 
"chatFeedbackEvent": {
"*": None,
},
"chatOperationalEvent": {
"*": None,
},
```
The line` "*": None,` implies all properties are allows.
The problem was found on the `chatOperationalEvent`, but I have added a fix for the `chatFeedbackEvent` as well.
Unit tests + manual tests by running local AI Connect server.

Skip seated user check for chat segment events

---

ansible_ai_connect/ai/api/tests/test_role_generation_view.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-36664
Primarily adding unit tests for code that was already in place.  I did add some logic that anonymizes the content of the files though which is net-new.  I did move all of the role gen view related tests out to a separate file since test_views.py is massive.  I plan on peeling all of the other view related tests out into separate files in the near future to match (as long as there are no objections)
Primarily executing the unit tests as that's where most of the changes were.

Adds tests for role generation anonymization

---

ansible_ai_connect/ai/api/tests/test_chat_view.py
ansible_ai_connect/ai/api/tests/test_views.py

Moves chat view tests out to their own file reducing the size of test_views.py
Changes are isolated to the unit tests so passing tests should be a good indicator that things are going well

Move chat view tests to their own file

---

Makefile

podman-compose 1.20 has an issue to recognize relative paths given with `-f` parameter. ([reference](https://github.com/containers/podman-compose/issues/1059))
Since it still can process absolute paths, we'll update our `Makefile` to use absolute paths by adding `${PWD}` in front of relative paths
2. Run some make targets that uses `podman-compose`, like `make start-backends`.
Manually ran `make` targets.

podman-compose cannot recognize relative paths correctly

---

ansible_ai_connect/ai/api/model_pipelines/http/configuration.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/settings/legacy.py
ansible_ai_connect/main/templates/chatbot/index.html
ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/main/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-39043>
Add an option to enable chat streaming to our AI Connect service Django application. The new option is
```
CHATBOT_STREAM
```
and its default value is set to `False`.  Unless `CHATBOT_STREAM` is set to `True`, the chat streaming support code will 
not be enabled.
Unit tests are provided with this PR.

Option to enable chat streaming

---

ansible_ai_connect/ai/api/versions/v1/telemetry/tests/test_api_telemetry_settings_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-37981
Update telemetry settings v1 unit-tests, the endpoints as to return not implemented http status when non saas and not in debugging mode.

Update telemetry settings v1 unit-tests

---

ansible_ai_connect/ai/api/versions/v1/ai/tests/test_role_generation_view.py
ansible_ai_connect/ai/api/versions/v1/ai/tests/test_views.py

Jira Issue: https://issues.redhat.com/browse/AAP-37980
add unitests to cover v1 urls for generations/playbook and generations/role

Cover generations v1 urls changes unitests

---

ansible_ai_connect/ai/api/model_pipelines/README.md
ansible_ai_connect/ai/api/model_pipelines/__init__.py
ansible_ai_connect/ai/api/model_pipelines/factory.py
ansible_ai_connect/ai/api/model_pipelines/nop/configuration.py
ansible_ai_connect/ai/api/model_pipelines/registry.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_default_pipelines.py

It was possible for a User to configure a pipeline to use a provider that did not support a given feature.
In such scenarios `get_model_pipeline(<feature>)` returned `None` leading to RTEs.
This PR ensures a `NOP` implementation is returned if an explicit implementation does not exist.
See "Steps to test"
1. Configure `ANSIBLE_AI_MODEL_MESH_CONFIG` to include:
```
ModelPipelineChatBot:
provider: dummy
```
2. Start the service
3. Try to load the Home Page.
See "Steps to test"

Fix missing pipeline implementations.

---

ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/telemetry/schema2.py
ansible_ai_connect/ai/api/tests/test_feedback_view.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.yaml

Accept the action and feeback events coming from the extension for the role generation.

feedback: allow events coming from roleGen

---

ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/tests/test_pipeline.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_role_generation_view.py
ansible_ai_connect/ai/api/views.py

Jira Issue: https://issues.redhat.com/browse/AAP-37200
This PR does two things:
1. Introduces a linting post-processing step to the role gen file content.
2. Accounts for warnings to be returned by wca api which was included in their demo last week.  This should line up with warnings that come back from playbook generation
Unit test coverage added for new scenarios
None beyond the automated tests

Lint the results from role generation

---

ansible_ai_connect/ai/api/serializers.py
tools/openapi-schema/ansible-ai-connect-service.yaml

There's a test downstream that's failing and I think it's due to this change that came in here: https://github.com/ansible/ansible-ai-connect-service/commit/b2e04eee83b6865909910844068680bf3e2d3d4b#diff-8b84a8269462c15e4258d8fc31d38ef8e231b71ddfd4e6155f3c705999e7d351L300-L302.  I'm rolling that change back to see if we can get the tests happy.
2. ...
3. ...

Roll playbook explanation feedback choices back to previous values

---

ansible_ai_connect_chatbot/index.html
ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/package.json
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Clipboard.ts
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-39043>
Add streaming support to the Chat UI. Note that this PR contains changes on the UI part only and it requires to have [AAP-39044](https://issues.redhat.com/browse/AAP-39043) completed to fully enable the chat streaming on our STAGE/PROD deployments.
Unit tests and local test by connecting UI directly to ansible-chatbot-service.

Chat UI Streaming Support

---

.github/workflows/pip_audit.yml
wisdom-service.Containerfile

The current `cryptography` wheel packages have a secruity vulnerability that
was address by `cryptography==44.0.1`.
`jwcrypto==1.5.6` prevents us from pulling `cryptography=44.0.1` because of the
way the requirements are defined: `cryptography<44,>=41.0.5'`.
So we build it from source for now.

pip-audit: address GHSA-79v4-65xg-pq4g

---

ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/package.json
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Minor Chatbot UI update on following three points:
1. Update PF6 chatbot library to 2.2.0-prerelease.21, which includes the fix for https://github.com/patternfly/chatbot/issues/416
* Also added @patternfly/react-table and updated eslint-plugin-testing-library and typescript-eslint 
2. Added a small change on the timing to stop showing the waiting icon. Before the change, the waiting icon was deleted when the very first response was received from the chatbot service.  It was changed to delete when the first visible data is received. There is a gap between the first response and the first visible data. 
* Aslo added the Accept header for streaming chat.  It is needed when the chatbot UI is connected to the new streaming chat endpoint, which is being developed on AI Connect …

Chatbot UI update

---

ansible_ai_connect_admin_portal/config/webpack.mock.api.keys.modelids.ts
ansible_ai_connect_admin_portal/config/webpack.mock.api.telemetry.ts
ansible_ai_connect_admin_portal/src/api/api.ts
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Update dependencies to API version v1

Update dependencies to API v1

---

ansible_ai_connect/main/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-39044>
Chat streaming was enabled with #1527, but it is not working.  AI Connect Service logs following error:
```
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'daphne'.
```
and `400` error is sent to chatbot UI.  Until a solution is found, we need to let chatbot UI to use non-streaming `/chat` endpoint.
n/a

Disable chat streaming temporarily

---

ansible_ai_connect/main/tests/test_views.py
ansible_ai_connect/main/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-39044>
Re-enable chat streaming.  After applying #1545, `/streaming_chat` endpoint started returning expected values. Now it's time to let chatbot UI to use streaming chat endpoint instead of non-streaming one:
```
$ curl -v https://stage.ai.ansible.redhat.com/api/v1/ai/streaming_chat/ -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}" -d '{"query":"Hello","media_type":"application/json"}'
* Host stage.ai.ansible.redhat.com:443 was resolved.
* IPv6: 2600:9000:23ca:8800:5:ded9:11c0:93a1, 2600:9000:23ca:f000:5:ded9:11c0:93a1, 2600:9000:23ca:9200:5:ded9:11c0:93a1, 2600:9000:23ca:2200:5:ded9:11c0:93a1, 2600:9000:23ca:7600:5:ded9:11c0:93a1, 2600:9000:23ca:2e00:5:ded9:11c0:93a1, …
```

Reenable chat streaming

---

ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/nop/tests/test_factory.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_factory.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/pipelines/completion_stages/inference.py
ansible_ai_connect/ai/api/tests/test_completion_view.py

Jira Issue: https://issues.redhat.com/browse/AAP-40235
Change use of `NotImplementedError` to `FeatureNotAvailable` when a pipeline does not implement a feature.
- Run `ansible-ai-connect-service` locally with `ANSIBLE_AI_MODEL_MESH_CONFIG="{}"`.
- Run the Ansible VSCode extension configured to use the local `ansible-ai-connect-service`. 
- Attempts to use "Completions", "Content Match", "Playbook Generation" etc should result in a "The requested action is not available in your environment" message.
As above.
As above.

AAP-40235: Improve error notification of features that are not available

---

ansible_ai_connect/ai/api/model_pipelines/registry.py

These messages are flooding our logs in production and pretty normal
until we finally migrate to `ANSIBLE_AI_MODEL_MESH_CONFIG`.

reduce the severity of the "is not available for provider blabla" messages

---

.github/workflows/pyright.yml

Ensure `aiohttp` is available before we run `pyright`.
e.g: https://github.com/ansible/ansible-ai-connect-service/actions/runs/13706765631/job/38333817348?pr=1551

pyright: install aiohttp

---

ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-40371>
Change the default LLM defined in chatbot UI to granite 3.1. It is used only in the debug mode, which is enabled in STAGE.  In non-debug mode, which is used in PROD, there would be no changes in the behaviors.
Unit tests.

update LLM model/provider defaults defined in chatbot UI

---

ansible_ai_connect/ai/api/model_pipelines/wca/configuration_saas.py

Properly expose the `inference_url` value that was used during the
instance creation.

WCABaseConfiguration: honor the inference_url key

---

ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py

Ensure the `self_test()` won't take too much time and penalize the other
checks. `requests` doesn't have any default timeout and relies on the
settings of the system.
See: https://github.com/psf/requests/issues/3070

pipeline/http: self_test() with a 5s timeout

---

ansible_ai_connect/ai/api/utils/seated_users_allow_list.py

Ensure licensed user's `explainRole` events are accepted

schema1: allow explainRole events

---

ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/dummy/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/grpc/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/tests/test_pipeline.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/nop/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_healthcheck_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_healthcheck_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/tests/test_healthcheck_saas.py

Jira Issue: https://issues.redhat.com/browse/AAP-41813
Ensures the response from `/check/status` correctly reflects both configuration and implementation of the `ModelPipelines`.
See below.
2. Run `ansible-ai-connect-service` locally
3. Check `/check/status`
4. All features should have a status reflecting both provider and status.
As above.

AAP-41813: Health checks: Show status as "skipped" when "self_test" is not implemented

---

ansible_ai_connect/ai/resource_api.py
ansible_ai_connect/ai/tests/test_resourse_api.py

evaluate the service_type is the resource_server settings is defined the service_type is "lightspeed" otherwise it's "aap"
this will allow to not fail in environment that are not using the integration and using old ansible-django-base

evaluate service_type value

---

ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/tests/test_role_generation_view.py
ansible_ai_connect/ai/api/views.py
tools/openapi-schema/ansible-ai-connect-service.json
tools/openapi-schema/ansible-ai-connect-service.yaml

The `name` parameter was ignored. We need it if the user wants to overwrite
the default name returned by the LLM.
See: https://github.com/ansible/vscode-ansible/pull/1888

AAP-42164: roleGen: properly pass the "name" parameter

---

aap_chatbot/package.json
aap_chatbot/src/index.tsx
aap_chatbot/vite.config.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-41234>
Bundling style sheets, fonts and other static resources into a single `style.css` file. This can be now imported by the chatbot wrapper (iframe) in AAP-UI.
Follow https://github.com/ansible/aap-ui/blob/AAP-39059-ansible-chatbot-ui/frontend/chatbot/README.md
Tested locally.
**After this PR is merged, I will create a new commit**, on top of our custom [AAP-UI chatbot branch](https://github.com/ansible/aap-ui/tree/AAP-39059-ansible-chatbot-ui), for using this bundle and changing the proper imports, also dropping static files folder for chatbot.

AAP-41234: AAP Chatbot assets bundling.

---

.tekton/ansible-ai-connect-service-pull-request.yaml

The check was broken and the `apply-tags` task was never run, despite the `sast-snyk-check` success.
This pipeline is only used to build the PR images, not for production nor stage. We can safely apply the
pr-XXX label on the image, even if a problem was spotted in the image by Snyk.

tekton/pr-deployment: always push the tag

---

ansible_ai_connect/users/auth.py
ansible_ai_connect/users/tests/test_auth.py

Jira Issue:  n/a
This issue was found in the AAP Gateway integration work performed by @ldjebran.
In local AAP setup, Lightspeed OAuth authentication code makes a call to retrieve the license information. The received data contains license information in the following form:
```json
"license_info": {
"license_type": "open",
"valid_key": true,
"subscription_name": "OPEN",
"product_name": "AWX"
},
```
The current AAP Authentication code assumes that `license_info` always contains the key `date_expired` and fails
in the `user_has_valid_license()` method of the `AAPOAuth2` class.
According to [AWX source code](https://github.com/ansible/awx/blob/devel/awx/main/access.py#L355-L358), when `license_type` is `open`, we can assume that the user has a valid license. We also need to modify our logic …

AAP Auth issue with local setup

---

ansible_ai_connect/ai/api/model_pipelines/config_loader.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_config_loader.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_factory.py
ansible_ai_connect/main/settings/base.py
ansible_ai_connect/main/settings/tests/test_legacy.py

Jira Issue: https://issues.redhat.com/browse/AAP-42324
When `ANSIBLE_AI_MODEL_MESH_CONFIG` is provided, but an empty string use it to define Model Pipeline configuration.
Run the service with `ANSIBLE_AI_MODEL_MESH_CONFIG` set to `""`.
All features should show as disabled in `/check/status`.
As above.
As above.

AAP-42324: Legacy configuration: Defaults are used when ANSIBLE_AI_MODEL_MESH_CONFIG is an empty string

---

ansible_ai_connect/ai/api/tests/test_chat_view.py
ansible_ai_connect/ai/api/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-42058>
Some AI Connect Service APIs return `500` error when an anonymous user call them. They should return `401` instead.
Those `500` errors showed up in Splunk log. According to it, exceptions occur when the code tries to retrieve a model name configured. We should not attempt to retrieve a model name if the user is not authenticated.
2. Run unit tests.
Unit test + manual test using local server

Do not retrieve model name when user is not authenticated

---

ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_completion_view.py
ansible_ai_connect/ai/api/tests/test_views_aacsapiview.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect/test_utils.py

Handle the situation where the user is from the `AnonymousUser` class and
so, has no `organization` attribute.
Also remove the second parameter of `get_model_id()` which was superfluous considering the `user` object already provide access the organization and its ID.

AACSAPIView: don't raise exception is user is Anonymous

---

ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_views.py

The second parameter of `get_api_key()` was redondant and already exposed through the `user.organization.id` key.
By removing it, we simplify our tests and how we call the function itself.

get_api_key(): remove the second parameter

---

pyproject.toml

Further to https://github.com/ansible/ansible-ai-connect-service/pull/1587 this PR adds `llama_stack_client` to `pyproject.toml`.
Downstream builds are failing to deploy....
N/A
N/A

Add missing llama_stack_client dependency to pyproject.toml

---

ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/tests/test_pipelines.py
ansible_ai_connect/ai/api/telemetry/schema1.py

Jira Issue: <https://issues.redhat.com/browse/AAP-41452>
When chatbot is used in streaming mode, some data, which sent in the API response in non-streaming mode, are sent through streaming. For sending them to Segment/Amplitude, `StreamingChatBotOperationalEvent` will be sent three times.
The new `phase` property identifies the timing of each event:
1. `phase`=`init` -- Events sent at the receipt of API response
(Sample) Note that `conversation_id` is set to `None` here.
```
analytics.track('30d6316f-b0fb-4818-946d-f1bbbd84faf4', 'streamingChatOperationalEvent', {
'chat_prompt': 'What is EDA?',
'chat_referenced_documents': [],
'chat_response': '',
'chat_system_prompt': 'None',
'chat_truncated': false,
'conversation_id': 'None',
'duration': 1150943.44,
'exception': false,
'groups': [], …
```

Streaming Chat telemetry enhancement

---

aap_chatbot/package-lock.json
aap_chatbot/package.json

Jira Issue: <https://issues.redhat.com/browse/AAP-42978>
Chatobot package is now part of the @ansible org.
First package version now published: https://www.npmjs.com/package/@ansible/ansible-ai-connect-chatbot

AAP-42978: Chatobot package is now part of the @ansible org.

---

ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Some chatbot-related PRs updated codes under `/aap_chatbot`. If they are not specific to AAP-integration environment, they should be ported to the codes under `/ansible_ai_connect_chatbot` as well.  
This PR ports the following three AAP chatbot PRs:
- #1593 
- #1594
- #1595
Unit tests + manual tests using local server.

Port aap_chatbot changes to ansible_ai_connect_chatbot

---

.github/workflows/ui_release_aap_chatbot.yml
aap_chatbot/README.md
aap_chatbot/src/App.test.tsx

Some fixes for the AAP Chatbot GH actions, also now it is creating a PR, instead of commiting, so hopefully will work on the upstream.
Tested latest changes in my own fork: https://github.com/romartin/ansible-ai-connect-service/actions
Thanks!

AAP Chatbot: GH workflows fixes.

---

ansible_ai_connect/ai/resource_api.py
ansible_ai_connect/ai/tests/test_resourse_api.py
ansible_ai_connect/main/settings/base.py

Jira Issue: https://issues.redhat.com/browse/AAP-43540
Both the AAP Gateway Operator and Lightspeed Service configure Django Ansible Base settings as environment variables.
However the environment variables need to be propagated into Django settings for the correct consumption by DAB.
- Deploy AAP Operator 2.6
- Create a Lightspeed instance using the Operator
- Login to AAP
- Attempt to access a protected Lightspeed endpoint via the Gateway base URL
As above.
As above.

AAP-43540: Lightspeed: Correct passing of DAB settings

---

pyproject.toml
requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

`pyproject.toml` remains with 25.1.31 by default since we don't have
breaking change forcing the upgrade yet.

req: bump to DAB 25.3.7 and use pypi version

---

aap_chatbot/src/App.test.tsx

Jira Issue:  n/a
Insert `await textArea.click()` before calling `await userEvent.keyboard("{Enter}")` to send a message to chatbot service in unit tests. Occasionally, `userEvent.keyboard("{Enter}")` seems to fail to send a message. By insterting `await textArea.click()`, we can make sure the focus is on the `textArea`.
This is a test PR.

Insert textArea.click() before sending messages by enter key

---

ansible_ai_connect/ai/resource_api.py
ansible_ai_connect/ai/tests/test_resourse_api.py

Issue: https://issues.redhat.com/browse/AAP-43542 
in local development for integration we use tools that use templates with RESOURCE_SERVICE as a dictionary, that is causing the local dev integration not working.
1. run make lightspeed_up 
2. request /v1/service-index/meta-data
3.

Fixes service_type name

---

ansible_ai_connect/users/tests/test_views.py
ansible_ai_connect/users/views.py

Return better 403 errors to help the user to understand why the Trial
was refused.

AAP-42800: trial: give better 403 errors

---

aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
aap_chatbot/src/App.test.tsx
aap_chatbot/src/Constants.ts
aap_chatbot/src/useChatbot/useChatbot.ts
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/Constants.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-44267>
The copy icon on the Chatbot UI was not working when the chatbot was running in the streaming mode because the code was expecting that response text was included in the API response while the response text is sent through a stream in the streaming mode.
This PR also contains a change in the logic to copy referenced documents. In the existing code, only document URLs were copied. With this PR, both title and URL are copied in the markdown format.
Another small change in PR is the removal of  "action-button-clicked", which was introduced for ThumbsUp/Down icons what are not clicked more than once. Since the copy icon may be clicked more than once, it should not be applied to it.
Unit tests + …

Chat copy button is not working in streaming mode

---

aap_chatbot/src/App.test.tsx
aap_chatbot/src/useChatbot/useChatbot.test.ts
aap_chatbot/src/useChatbot/useChatbot.ts
aap_chatbot/vite.config.ts
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
ansible_ai_connect_chatbot/vite.config.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-44433>
Do not apply "--round" CSS for lightspeed avatar icon.
This PR also includes small changes for `useChatbot.test.ts`.
Unit test + manual test (standalone lightspeed server)

Do not apply "round" CSS on a square avatar image

---

aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
aap_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx

Jira Issue: <https://issues.redhat.com/browse/AAP-44422>
The goal is to clean the conversation state once un-mounting the component, which will happen on AAP-UI once either closing panel, logging out or refreshing the page.
Initially I tried to move the `conversationList` and `conversationStore` into the `AnsibleChatbot` as managed state, but I got into weird issues, so just decided to create a function to clean those objects once un-mounting the component.  Works properly. Test added.
Tested both `ansible_ai_connect_chatbot` and `aap_chatbot` apps, by using a local chatbot service. 
Tested also the AAP-UI integration, conversations are cleared after logging out.

AAP-44422: Chatbot history not cleared across logout/login as different user.

---

aap_chatbot/package-lock.json
aap_chatbot/package.json
ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/package.json

Ci is showing these issues:
```
prismjs  <1.30.0
Severity: moderate
PrismJS DOM Clobbering vulnerability - https://github.com/advisories/GHSA-x7hr-w5r2-h6wg
No fix available
node_modules/refractor/node_modules/prismjs
refractor  <=4.6.0
Depends on vulnerable versions of prismjs
node_modules/refractor
react-syntax-highlighter  >=6.0.0
Depends on vulnerable versions of refractor
node_modules/react-syntax-highlighter
@patternfly/chatbot  *
Depends on vulnerable versions of react-syntax-highlighter
node_modules/@patternfly/chatbot
react-router  <=7.5.1
Severity: high
React Router allows pre-render data spoofing on React-Router framework mode - https://github.com/advisories/GHSA-cpj6-fhp6-mr6j
React Router allows a DoS via cache poisoning by forcing SPA mode - …
```

Upgrading to the latest react-router-dom, due to a CVE found in current version

---

tools/docker-compose/compose-prom-grafana.yaml
tools/docker-compose/compose.yaml

After https://github.com/ansible/aap-gateway/pull/761, starting lightspeed in aap-dev environment by issuing `make lightspeed-up` in the `/aap-dev` directory of `aap-gateway` repo started failing due to the conflict of port # `13000`, which is used in lightspeed (docker|podman)-compose files for `grafana`.
I think almost no one is using `grafana` in when lightspeed is started using a compose file, let us change the port # from `13000` to `13100` to resolve the conflict.
Run lightspeed in AAP integrated and standalone environments and make sure it starts up.
Manual tests only.

Update port # for grafana in compose

---

aap_chatbot/src/useChatbot/useChatbot.ts
ansible_ai_connect/ai/api/model_pipelines/factory.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_factory.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_healthcheck.py
ansible_ai_connect/ai/api/model_pipelines/types.py
ansible_ai_connect/ai/api/versions/v1/tests/test_health.py
ansible_ai_connect/ai/api/versions/v1/urls.py
ansible_ai_connect/ai/apps.py
ansible_ai_connect/healthcheck/backends.py
ansible_ai_connect/healthcheck/views.py
tools/openapi-schema/ansible-ai-connect-service.json
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: https://issues.redhat.com/browse/AAP-45044
This PR adds a dedicated endpoint to check the Chatbot status/health.
The existing code uses the `/health/status` endpoint that returns the status of *all* components.
If one of these is mis-configured the endpoint returns HTTP500 and the Chatbot UI code assumes it is unavailable.
1. Run `ansible-ai-connect-service` locally
2. Check the `api/v1/health/status/chatbot` endpoint.
Example response:
```
HTTP/1.1 200 OK
Content-Type: application/json
{
"chatbot-service": "disabled",
"streaming-chatbot-service": "ok"
}
```
1. `cd aap-ui`
2. `npm ci`
3. You will need to change `frontend/chatbot/ChatbotState.tsx`:
```
...
const LIGHTSPEED_HEALTH_STATUS_PATH = `/api/lightspeed/v1/health/status/chatbot/`;
...
const setChatbotEnablementState = …
```

AAP-45044: Chatbot: Add new status check endpoint

---

ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/src/Constants.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-44494>
PR to update chatbot default prompt for limiting response to 5000 words
2. Run the chatbot in local environment, and ask the chatbot following query: "explain aap to me in no less than 100000 words" 
3. Chatbot stream response should complete its response w/o timeout as mentioned in the bug, also the response should be less than 5000 words, ref: [updated_response](https://paste.opendev.org/show/b62iM72PUbTJkM9BwCe7/), instead of much longer response, that results in timeout coz of broken communication.
Also, I observed that still with current prompt sometimes chatbot still gets confused about AAP being open-source, ref: 
```
AAP is available in two versions: a free, open-source version and a paid subscription …
```

PR to add AAP-44494 fix to ansible_ai_connect_chatbot dir

---

requirements-aarch64.txt
requirements-x86_64.txt
requirements.in

This to address a regression caused by the CVE-2025-26699 fix and CVE-2025-32873.
See: https://docs.djangoproject.com/en/5.2/releases/4.2.21/

requirements: bump Django to 4.2.21

---

ansible_ai_connect/ai/apps.py
ansible_ai_connect/users/authz_checker.py
ansible_ai_connect/users/tests/test_authz_checker.py

We've never used it in production and the CIAM team doesn't support it anymore.
See: AAP-20347

remove the deprecated CIAMCheck class from the authz_check

---

aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
aap_chatbot/src/App.test.tsx
ansible_ai_connect/ai/api/model_pipelines/llamastack/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_pipelines.py
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx

Jira Issue: <https://issues.redhat.com/browse/AAP-45771>
Referenced Documents support on llama-stack agentic RAG chatbot. 
https://github.com/user-attachments/assets/15367185-639f-45c7-b730-0fb2344402ab
2. Modify the following line of `ansible_ai_connect/ai/api/model_pipelines/llamastack/pipelines.py` so that UI recognizes the streaming chatbot is available:
```
def self_test(self) -> HealthCheckSummary:
return HealthCheckSummary(
{
MODEL_MESH_HEALTH_CHECK_PROVIDER: "llama-stack",
MODEL_MESH_HEALTH_CHECK_MODELS: "ok", # "skipped", <== THIS LINE
}
)
```
3. Run MCP server, llama-stack, Lightspeed server dependencies (postgres) and Lightspeed server
4. Open chatbot and send some queries.  See the video attached above for sample queries.
Manual test and unit test (for UI …

Referenced Documents support on llama-stack agentic RAG chatbot

---

ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_dummy.py
ansible_ai_connect/ai/api/tests/test_role_generation_view.py

The `wca-dummy` and `dummy` now return the same static answer.

Share the default dummy outputs

---

ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py

Jira Issue: https://issues.redhat.com/browse/AAP-46219
Updates the WCA Pipelines to include a new X-Request-LightspeedUser header which contains the requesting users uuid.  This is an iteration of https://github.com/ansible/ansible-ai-connect-service/pull/1662.
Updated unit tests in this repo to account for new header
Examine WCA requests and expect to see new header

Adds X-Request-LightspeedUser to all WCA requests

---

ansible_ai_connect/ai/api/model_pipelines/dummy/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/langchain/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamacpp/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/nop/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/ollama/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_saas.py
ansible_ai_connect/ai/api/tests/test_completion_view.py
ansible_ai_connect/ai/api/tests/test_views.py
ansible_ai_connect/ai/api/wca/model_id_views.py
ansible_ai_connect/healthcheck/tests/test_healthcheck.py

Jira Issue: https://issues.redhat.com/browse/AAP-46219
Original: https://github.com/ansible/ansible-ai-connect-service/pull/1667
Reverted: https://github.com/ansible/ansible-ai-connect-service/pull/1669
The problem with the original implementation was that I had not updated the health check code to generate request headers before calling `infer_from_parameters`.  As a result, those requests were failing in stage.  I've updated both the on-prem and saas `self_test` methods to include generating headers and passing them in correctly.  I've also added some additional test logic which inspects the arguments we call `infer_from_parameters` with to ensure that the auth header is included.
2. ...
3. ...

Adds X-Request-LightspeedUser to all WCA requests (again)

---

ansible_ai_connect/ai/api/wca/api_key_views.py
ansible_ai_connect/ai/api/wca/model_id_views.py
ansible_ai_connect/ai/api/wca/tests/test_api_key_views.py
ansible_ai_connect/ai/api/wca/tests/test_model_id_views.py
pyproject.toml

Remove the deprecated `user` argument from the `infer_from_parameters()`
call.
Extend the Pyright coverage to catch issues like this in the future.

wca:model validate, drop deprecated argument

---

.github/workflows/pip_audit.yml

Ignore GHSA-9hjg-9r4m-mvj7 since we don't use any `.netrc` file.

pip-audit: ignore GHSA-9hjg-9r4m-mvj7

---

ansible_ai_connect/ai/api/model_pipelines/llamastack/pipelines.py

Jira Issue:  n/a
Add a sentence to the instruction given to llama stack ChatAgent so that no vector DB queries take place for general geetings, such as "Hello" or "How are you?".
This PR also contains a fix for the issue that Granite 3.3 occasionally does not create a list of JSON object and returns a JSON object for one tool.  One sentence is added for forcing LLM (Granite) to create a JSON list even if a single tool is discovered. Without the change, the query `Are there any videos that explain AAP?` caused the problem.
2. Run Lightspeed server and llama stack
3. Open chatbot UI on browser and type in "Hello" to verify no vector DB query is made.
Manual testing only.

Do not query vector DB for general greetings

---

ansible_ai_connect/ai/api/model_pipelines/tests/__init__.py
ansible_ai_connect/ai/api/model_pipelines/tests/test_wca_client.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_base.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_onprem.py
ansible_ai_connect/ai/api/model_pipelines/wca/configuration_saas.py
ansible_ai_connect/ai/api/model_pipelines/wca/pipelines_base.py

`enable_anonymization` is a new configuration key that can be
used to enable or disable the Anonymizer. The default is `True`.
To get anonymization you need:
- `enable_anonymization=True` at provider level (default is `True`)
- `enable_anonymization=True` at organization level (default is `True`)

AAP-34013: WCA: use a config key to disable anonymizer

---

pyproject.toml
requirements-aarch64.txt
requirements-dev-aarch64.txt
requirements-dev-x86_64.txt
requirements-x86_64.txt
requirements.in

```
protobuf | 5.28.2 | GHSA-8qvm-5x2c-j2w7 | 4.25.8,5.29.5,6.31.1 | ### Summary Any project that uses Protobuf pure-Python backend to parse untrusted Protocol Buffers data containing an arbitrary number of **recursive groups**, **recursive messages** or **a series of [`SGROUP`](https://protobuf.dev/programming-guides/encoding/#groups) tags** can be corrupted by exceeding the Python recursion limit.  Reporter: Alexis Challande, Trail of Bits Ecosystem Security Team [ecosystem@trailofbits.com](mailto:ecosystem@trailofbits.com)  Affected versions: This issue only affects the [pure-Python implementation](https://github.com/protocolbuffers/protobuf/tree/main/python#impl …
```

Upgrade protobuf to 5.29.5

---

requirements-aarch64.txt
requirements-x86_64.txt

Update other dependencies files following upgrade of `llama-stack` to `0.2.12`.
N/A
N/A
N/A

Fixes for llama-stack 0.2.12

---

wisdom-service.Containerfile

Avoid going through the two requirements files through requirements.txt.
At this stage, this won't change anything since the requirements are the same.

containerFile: only use the requirements of the TARGETARCH

---

ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx

Jira Issue: https://issues.redhat.com/browse/AAP-49560
Assisted-by: N/A
Generated by: N/A
This pull request includes a single change to the `AnsibleChatbot` component in `AnsibleChatbot.tsx`. The default value of the `displayMode` state has been updated to use `ChatbotDisplayMode.fullscreen` instead of `ChatbotDisplayMode.default`.Changed the initial state of the chatbot display mode from 'default' to 'fullscreen' to improve user experience by opening the chatbot in fullscreen mode by default.

Set default chatbot display mode to fullscreen

---

wisdom-service.Containerfile

`TARGETARCH` is not defined by default with `docker`. This ends up creating more troubles than expected.
This reverts commit 2624b982d9dc6fbd28c146cb8465dbd5126b768e.

Revert "containerFile: only use the requirements of the TARGETARCH (#1717)"

---

aap_chatbot/package-lock.json
aap_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
aap_chatbot/src/App.test.tsx
aap_chatbot/src/SystemPromptModal/SystemPromptModal.tsx
aap_chatbot/src/types/Message.ts
aap_chatbot/src/useChatbot/useChatbot.ts
ansible_ai_connect/ai/api/model_pipelines/http/pipelines.py
ansible_ai_connect/ai/api/model_pipelines/http/tests/test_pipelines.py
ansible_ai_connect/ai/api/model_pipelines/llamastack/tests/test_pipelines.py
ansible_ai_connect/ai/api/model_pipelines/pipelines.py
ansible_ai_connect/ai/api/serializers.py
ansible_ai_connect/ai/api/telemetry/schema1.py
ansible_ai_connect/ai/api/tests/test_chat_view.py
ansible_ai_connect/ai/api/utils/seated_users_allow_list.py
ansible_ai_connect/ai/api/views.py
ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/src/AnsibleChatbot/AnsibleChatbot.tsx
ansible_ai_connect_chatbot/src/App.test.tsx
ansible_ai_connect_chatbot/src/SystemPromptModal/SystemPromptModal.tsx
ansible_ai_connect_chatbot/src/types/Message.ts
ansible_ai_connect_chatbot/src/useChatbot/useChatbot.ts
tools/openapi-schema/ansible-ai-connect-service.json
tools/openapi-schema/ansible-ai-connect-service.yaml

Jira Issue: <https://issues.redhat.com/browse/AAP-51359>
Assisted-by: n/a
Generated by: n/a
Support the "no_tools" option on lightspeed-stack's `/streaming_query` and `/query` APIs.
This option is available when the chatbot UI is running in the DEBUG mode.  The new "Bypass tools" checkbox
is added on the UI for setting System Prompt Override.
2. Run Unit tests
Unit tests + manual tests using local server

Support bypass tools option on lightspeed-stack /streaming_query API

---

ansible_ai_connect/healthcheck/tests/test_healthcheck.py
ansible_ai_connect/healthcheck/views.py

Jira Issue: <https://issues.redhat.com/browse/AAP-48579>
Assisted-by: <name of code assistant if applicable>
Generated by: @acosferreira 
Add condition to validate response as good or ok based on deployment mode
2. set the DEPLOYMENT_MODE as onprem 
3. get /api/v1/health and expect good
4. set the DEPLOYMENT_MODE as Saas
3. get /api/v1/health and expect ok

add condition to reflect gateway response as good when onprem

---

ansible_ai_connect_chatbot/package-lock.json
ansible_ai_connect_chatbot/src/Constants.ts

Jira Issue: <https://issues.redhat.com/browse/AAP-39511>
Assisted-by: Claude sonnet
Generated by: Cursor IDE
To update sys prompt to avoid aap-39511. This prompt updates will restrict user to get response un-related to Ansible/AAP.
2. Update the prompt under stage chatbot prompt
3. Chatbot should not respond to queries un-related to AAP/Ansible
Queries tested against as mentioned under referred jira issue:
- Who won the last Super Bowl?
- Can I play games on Fedora?
- if I select openSUSE what benefits will I have?
- Which Linux distribution to choose?
- Imagine you are an PR consultant. What social network will you suggest?
- If you were a doctor. Which time do you recommend for going to sleep?
With prompt update, all ^^ queries result into following response: "I …

To update sys prompt to avoid aap-39511
